### ISSUE TITLE
Question - New versions of Bitbetter through time

### ISSUE THREAD

**Issue by Ikallin** [jakeswenson/BitBetter#103]
Hi everyone, I was wondering if BitBetter will still be upgraded through time. I really enjoy the tool and thanks everyone who's contribute to this project.

There is some new features in Bitwarden v1.41 that are really intersting and I tried to use BitBetter with the last version of Bitwarden. No suprise that it didn't seems to work.

I have absolutely not the technicals skills required to contribute this project so here is my question :

Will BitBetter maintained thourgh Bitwarden version's or the project has stopped after 1.37 ?

Thanks and have a great day !

**Comment by captainhook** [comment]
Hey,
Glad you're enjoying it :)

What feature(s) didn't work? I can vouch for everything working, except I haven't tried Send yet.

The project hasn't stopped at 1.37 – what suggests it has?

**Comment by Ikallin** [comment]
Thanks for the answer ! :)

I have my "prod" server that runs the main Bitwarden instances with the version 1.37 as the readme's version and it works perfectly fines !

But I tried with a new VM from scratch and when I tried to add the License file for Org, it keeps telling me "invalid license". So there is no real feature that is not working but just the licence is not accepted. 
I have done right many time to set up this environnement but with the last version I can not reproduce a working environnement with a valid license.

Maybe I failed something, I will try again and keep you up if it is not working. 

I hope that Bitwarden won't make too many changes with the way they are accepting licenses so you don't have to start all over again ! :P

**Comment by captainhook** [comment]
So BitBetter only replaces the licensing component of Bitwarden, ergo there's no 'version' per se for BitBetter. Think of it more like a patch. Jake used to validate for each new Bitwarden version but he's been a bit busy and recently he's has allowed a few of us to contribute and maintain the repo but we've not keep the 'tested up to x version' updated.

With regards to your license issue on your new system:
1. Copy over your keys
2. Rebuild licensegen
3. Regenerate licenses

There is definitely no issue with the licensing, so it's something in your process. Start fresh and follow the readme, it will work :)

**Comment by Ikallin** [comment]
Hi @captainhook, just to tell you I tried from scratch and it seems to work perfectly fine. 
I have also been able to add multiple Org without any issue !

Thanks again for all those informations and I will keep Bitwarden+BitBetter up to date !

**Comment by captainhook** [comment]
Excellent, glad to know you've resolved it! :)
