### ISSUE TITLE
Your docker file bitbetter/api not available

### ISSUE THREAD

**Issue by jonneolie** [jakeswenson/BitBetter#11]
Hello Jake,

I'm unable to locate your bitbetter/api. Can you place it on dockerhub again please?

Thanks,

**Comment by jakeswenson** [comment]
@jonneolie thanks for asking, but i've never published this to docker hub. If you want to use this project then you're free to build from source as others have done.

Thanks for asking though

**Comment by JeffAlyanak** [comment]
@jonneolie If you're getting that message about bitbetter/api not being found it means that you haven't successfully built it yet.

If you follow through the instructions in the `ReadMeInstall` document you should be able to successfully build the bitbetter/api before attempting to start bitwarden with it.




_Notes if you're interested: You'll see that there's a `Dockerfile` in the `BitBetter/src/bitBetter/` directory that first sources the official `bitwarden/api` and then modifies some stuff. It's really just a few minor changes to the original container, and it'll copy in your generated keys so it really doesn't need to be published on docker hub._
