### ISSUE TITLE
Workaround: The framework 'Microsoft.NETCore.App', version '3.1.0' was not found.

### ISSUE THREAD

**Issue by toni-1** [jakeswenson/BitBetter#115]
🐛 
You get 2 errors: 

+ dotnet /bitBetter/bitBetter.dll
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
  - The following frameworks were found:
      5.0.9 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Search for "3.1.0" and replace it with "5.0.9":
grep -iR "3.1.0" *
src/bitBetter/bin/Debug/netcoreapp3.1/bitBetter.runtimeconfig.json:      "version": "3.1.0"
src/bitBetter/bin/Debug/netcoreapp3.1/publish/bitBetter.runtimeconfig.json:      "version": "3.1.0"

Start the update (docker-compose override: yes and rebuild BitBetter images: yes):
./update-bitwarden

**Now the update is working.**

**Comment by captainhook** [comment]
Are you experiencing #114 after this?

**Comment by clanto007** [comment]
To resolve I did a similar thing:
I replaced the strings:
mcr.microsoft.com/dotnet/core/sdk:3.1
with:
mcr.microsoft.com/dotnet/sdk
in files:
\build.sh
\src\licenseGen\Dockerfile

After I changed:
netcoreapp3.1
with:
netcoreapp5.0
in:
\src\bitBetter\bitBetter.csproj
\src\bitBetter\Dockerfile
\src\licenseGen\Dockerfile
\src\licenseGen\licenseGen.csproj

Whit these changes I tried with new installlation, to upgrade installation and to add new org license, all is fine for now.
I tried also to add new password in personal and organization vault and all is right.

**Comment by toni-1** [comment]
@captainhook 
No problems like you mentioned in #114. 
iPhone App, Chrome Plugin and web is working an you can add new entries

**Comment by captainhook** [comment]
@toni-1 @clanto007 @mg-100 thank you all for checking for feeding back.
I'll work on a fix for this but I'm not available until next week. If anyone else can create a proper fix and submit PR that would be a great help.

**Comment by clanto007** [comment]
@captainhook I submitted now a PR, can you check if it's all right?

**Comment by MidavSec** [comment]
Same issue here, not really able to use as licenseGen is as well affected.
