### ISSUE TITLE
identity removing premium

### ISSUE THREAD

**Issue by maaeps** [jakeswenson/BitBetter#12]
Whenever I restart the identity server and login at the web interface I get this the identity pod logs this:
```
[40m[32minfo[39m[22m[49m: Bit.Core.Services.LicensingService[12482444]
      Validating premium license for user ********-****-****-****-************(user@domain.tld).
[40m[32minfo[39m[22m[49m: Bit.Core.Services.LicensingService[12482444]
      User ********-****-****-****-************(user@domain.tld) has an invalid license and premium is being disabled. Reason: Invalid signature.
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 2265.6261ms 200 application/json; charset=UTF-8
```

After this my premium state is obviously gone and I have to reupload my license.

I build my own api image due to the instructions.

Do I have to build a custom identity image as well?
And if yes: Are there other images I have to rewrite as well?

**Comment by maaeps** [comment]
After some try and error I figured out the /app/Core.dll of the image bitwarden/identity has to be overridden by the generated Core.dll as well.
I simply copied the Core.dll of the built api image into the identity image.

**Comment by JeffAlyanak** [comment]
@maaeps Did it need anything aside from the modified `/app/Core.dll`?

**Comment by JeffAlyanak** [comment]
Okay, this updated build script works for me in testing, might be worth reviewing as a candidate for inclusion in the develop and eventually master branches.

**Comment by maaeps** [comment]
I think back when I pulled the repository the first time, I had some issue as well which was fixed the fork of online-stuff. But I do not know if this was fixed already.

But this "forgetting issue" was fixed by just replacing the Core.dll of the images with the build one.

**Comment by JeffAlyanak** [comment]
> But this "forgetting issue" was fixed by just replacing the Core.dll of the images with the build one.

Okay, 4d4b17334499b0191577df6dc8f33a14f9e50906 should fix that by generating a bitbetter/api image for you with the modified Core.dll. At some point that will likely be merged into the master version.

**Comment by JeffAlyanak** [comment]
Closing this as these changes are ready to be merged now ( https://github.com/jakeswenson/BitBetter/pull/14 ).
