### ISSUE TITLE
licenseGen non-interactive needs storage arg

### ISSUE THREAD

**Issue by JollyBGood** [jakeswenson/BitBetter#122]
Using the supplied help to create an org license, it does not work without supplying an extra argument for storage.

`./src/licenseGen/run.sh /Absolute/Path/To/BitBetter/.keys/cert.pfx org "Name" "EMail" "Install-ID used to install the server"`

This creates an error, only when I also include storage (it tells me the default is 32767, so I use that). By providing this fourth parameter, the license is generated non-interactive.
`./src/licenseGen/run.sh /Absolute/Path/To/BitBetter/.keys/cert.pfx org "Name" "EMail" "Install-ID used to install the server" 32767`

To make it simpler, I would suggest just using the default as the value if none is specified, otherwise the readme/help need to be updated to reflect the required 4th argument.

**Comment by sutidor** [comment]
It has been implemented it seems:
Usage:  org [arguments] [options]

Arguments:
  Name          your name
  Email         your email
  InstallId     your installation id (GUID)
  Storage       Extra storage space in GB. Maximum is 32767 (optional)
  BusinessName  name For the organization (optional)
  Key           your key id (optional)
when using the dll, storage and businessname are required and only last one (key) is optional

**Comment by JollyBGood** [comment]
Sorry, I was not maybe so clear. I the documentation mentions the storage arg as optional, but it is in fact required. I would think instead it should default to the 32767 (which I believe is the intended default) if the argument is not supplied.

**Comment by sutidor** [comment]
I use this one, because it is actively developed and alexyao's docker versions (which is based on this one). Dunno if h44z is actively developed.

**Comment by robina80** [comment]
`/bitwarden/bwdata/BitBetter-master/src/licenseGen/run.sh /bitwarden/bwdata/BitBetter-master/.keys/cert.pfx org "$name" "$owner" your-installation-ID 32767 "$company"`

**Comment by h44z** [comment]
> I use this one, because it is actively developed and alexyao's docker versions (which is based on this one). Dunno if h44z is actively developed.

I only contribute to jakeswenson/BitBetter and suggest using this repository.
