### ISSUE TITLE
licenseGen output has extra non-printable characters

### ISSUE THREAD

**Issue by JollyBGood** [jakeswenson/BitBetter#123]
When I try to redirect the output of licenseGen in non-interactive to a .json file for uploading to the org, there are extra characters.
So instead of the first line simply being open braces
`{`
I get
`^[[?1h^[={`

This causes the .json file to be an invalid license when I try to apply it to the organization. I had to use a maze of sed commands to be able to correctly generate a usable .json file. I found that when I tried to strip the original first characters above by removing the first line, I was getting CRLF format (possibly due to the echo/sed combination), so I had to further convert to LF.

Currently I have to use this monstrosity:
`(echo "{" && ./src/licenseGen/run.sh /path/to/BitBetter/.keys/cert.pfx org "Name" email@domain.tld Install-ID-Here 32767 "BusinessName" |sed '1d') |sed $'s/\r$//' > /path/of/OrgLicense.json`

**Comment by robina80** [comment]
tell me about it, i have made a script where it emails them the json file (as an attachment) and includes all the extra special characters, in the email body i just say "delete the extra special characters after {"

**Comment by JollyBGood** [comment]
For a workaround, I use a combination of sed and tr.

Pipe your licenseGen run.sh command to :

`| tr -dc '\11\12\40-\176' |sed 's/\[?1h={/{/g'`

This cleans the file for import. Now I just need to figure out how to update the license file automatically

**Comment by JollyBGood** [comment]
My license becomes invalid every time I update my LE certs, so every 2 months or so, I have to do this. I'm guessing this isn't a problem if behind a reverse proxy? So for me, I would wish to automate applying the license file automatically. But this issue is just to see if we can somehow clean up the output without having to run the above commands on it every time

**Comment by robina80** [comment]
im not behind a reverse proxy and i dont have this issue, ive never had to update my org license, there always 100 years expiration date and by then, its not my problem

**Comment by JollyBGood** [comment]
@robina80 and you use a Let's Encrypt cert that you have to renew every 3 months? I think that's where the difference is, but if you do use an LE cert and don't have this issue, I need to have a side conversation and see what you're doing differently.

**Comment by robina80** [comment]
answer to the original question, found a way just using sed

`sed -i '1s/^.*[[:punct:]]*.$/\{/' /license_files/IT.json`

**Comment by h44z** [comment]
might have something to do with docker (for example: https://hjerpbakk.com/blog/2019/10/07/docker-bash-and-invisible-characters), need to check
