### ISSUE TITLE
Missing Enterprise Policy

### ISSUE THREAD

**Issue by japerlman** [jakeswenson/BitBetter#126]
Not sure if this user error but does the license generated by bitbetter enable all enterprise features? I'm missing the 'Master Password Reset' policy, it seems like I'm getting an 'organization' license and not an 'enterprise' license.

Am I doing something wrong or is this to be expected?

**Comment by captainhook** [comment]
That is odd. I have generated an Organisation license (as far as I know there's only user and org), and I have Master Password Reset feature.

Have you activated Admin Password Reset?
https://bitwarden.com/help/article/admin-reset#activate-admin-password-reset

**Comment by japerlman** [comment]
I go there to turn it on but my instance is missing that 'policy' to configure or enable. If you go there on yours, do you have a different list of policies to configure?

![image](https://user-images.githubusercontent.com/16259817/149587515-e02c5896-ecfc-4cbe-b066-bfda04260985.png)

**Comment by camelstrike** [comment]
@japerlman which version are you running?

on Server 1.42.3 and Web 2.22.3 I do see it

Do you see the policies config here? https://BITWARDEN/portal/policies

**Comment by hegedussz** [comment]
1.Generate a new license
2. Add a this line in the license file:
`"UseResetPassword": true,` 
3. Update the license
4. Log off-on Bitwarden safe
