### ISSUE TITLE
Produced licence generates an error: Version 6 is not supported

### ISSUE THREAD

**Issue by tfboy** [jakeswenson/BitBetter#130]
Testing on a fresh install of BW 1.46.2 / 2.26.1, I can generate the licence but the resulting JSON file is not accepted and BW has an error message top right when clicking Submit saying Version 6 is not supported.
I've tried changing it to different values, but the error remains. Removing it completely from the licence fails says Version 0 is not supported.

I guess the issue might not be a version number but something else and it just stumbles at the version value?

Apologies, I realised in editing the docker file, I had removed the version on the suffix part of the edit.

**Comment by h44z** [comment]
This is strange, version 1.46.x supports organization licenses up to version 8. Are you sure about the Bitwarden version?

**Comment by h44z** [comment]
Closed due to inactivity.
