### ISSUE TITLE
Update / Restart Error "yaml.scanner"

### ISSUE THREAD

**Issue by mrventerj** [jakeswenson/BitBetter#131]
Hello Gents

Has something changed that I need to update?

When trying to update my BW  to get a new cert I get the following:

bitwarden.sh version 1.47.1
Docker version 19.03.13, build 4484c46d9d
docker-compose version 1.27.3, build 4092ae5d

ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
  in "/home/LocalAdmin/bwdata/docker/docker-compose.override.yml", line 5, column 25
Bitwarden update completed!

And when trying to restart:
ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
  in "/home/LocalAdmin/bwdata/docker/docker-compose.override.yml", line 5, column 25
ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
  in "/home/LocalAdmin/bwdata/docker/docker-compose.override.yml", line 5, column 25

**Comment by mrventerj** [comment]
The  docker-compose.override.yml in the update script adds two colons after 

image: bitbetter/api:
and
bitbetter/identity:

I removed the colons and chose not to recreate the override during the update prompts.

The update then goes a step further then before and attempts to pull the new files, I then get the following errors:

ERROR: for api  pull access denied for bitbetter/api, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

ERROR: for identity  pull access denied for bitbetter/identity, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
ERROR: pull access denied for bitbetter/identity, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

This is my docker-compose.override.yml config if i choose not to override:

version: '3'

services:
  api:
    image: bitbetter/api

  identity:
    image: bitbetter/identity


Any advice?

**Comment by captainhook** [comment]
Rebuild BitBetter and that should resolve this issue

**Comment by mrventerj** [comment]
@captainhook  Thank you for the response.

I attempted the rebuild, by running the following- is this correct?:
From the BitBetter directory, simply run:

./build.sh

I got the following error:

 Determining projects to restore...
  All projects are up-to-date for restore.
  bitBetter -> /bitBetter/bin/Debug/netcoreapp3.1/bitBetter.dll
  bitBetter -> /bitBetter/bin/Debug/netcoreapp3.1/publish/
Sending build context to Docker daemon   2.85MB
Step 1/6 : ARG BITWARDEN_TAG
Step 2/6 : FROM ${BITWARDEN_TAG}
invalid reference format
Sending build context to Docker daemon   2.85MB
Step 1/6 : ARG BITWARDEN_TAG
Step 2/6 : FROM ${BITWARDEN_TAG}
invalid reference format
Error parsing reference: "bitbetter/api:" is not a valid repository/tag: invalid reference format
Error parsing reference: "bitbetter/identity:" is not a valid repository/tag: invalid reference format

**Comment by mrventerj** [comment]
These are the refrences I have in my build file where the reference issue occurs:

docker build --no-cache --build-arg BITWARDEN_TAG=bitwarden/api:$BW_VERSION --label com.bitwarden.product="bitbetter" -t bitbetter/api "$DIR/src/bitBetter"$
docker build --no-cache --build-arg BITWARDEN_TAG=bitwarden/identity:$BW_VERSION --label com.bitwarden.product="bitbetter" -t bitbetter/identity "$DIR/src/$

**Comment by mrventerj** [comment]
@captainhook 
I saw my build.sh was still referring to an older framework 3.
I replace my build.sh file with the latest one, I get the following errors now:

+ dotnet /bitBetter/bitBetter.dll
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
  - The following frameworks were found:
      5.0.15 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.0&arch=x64&rid=debian.10-x64

**Comment by mrventerj** [comment]
Nothing worked, restored this BW VM to a week old backup, changed the Bitwarden server's Weekly backups to Daily backups. as this was irreparable and I don't trust this at all, I even tried the workaround in this:
[](https://github.com/jakeswenson/BitBetter/issues/115.)

So I have a working BW now,  but how do I go about updating BW now? 
./update-bitwarden.sh is what caused this in the first place

**Comment by mrventerj** [comment]
Deleted the BitBetter folder, cloned in again, ran the build.sh, had to delete existing docker containers for some reason. (Parent images or something)
Updated and working.

**Comment by mrventerj** [comment]
Thanks for the response, hope you get well.
 I somehow figured it out after trying a bunch of stray punches.  The lesson learned: should have been running daily backups instead of weekly on my password server. Thanks for the efforts on this project to you and the team. @h44z  *Saw the merge just now.
