### ISSUE TITLE
how to know if works with bitwarden x version

### ISSUE THREAD

**Issue by robina80** [jakeswenson/BitBetter#141]
hi all,

looking at the admin portal, seems, they have changed there version numbering

https://i.postimg.cc/vZxK47Rf/versions.png

how do i know if bitbetter works with the new version of bitwarden, i usually wait few versions then run my upgrade script, is there a link where it says bitbetter works with bitwarden x

thanks,
rob

**Comment by anhnvme** [comment]
latest still ok. feel free to upgrade

**Comment by robina80** [comment]
thanks @anhnvme 

is there a table where it shows what version of bitbetter works with what version of bitwarden somewhere?

**Comment by anhnvme** [comment]
> thanks @anhnvme
> 
> is there a table where it shows what version of bitbetter works with what version of bitwarden somewhere?

Try with your homelab. And wait upgrade when have trouble.

**Comment by captainhook** [comment]
> thanks @anhnvme
> 
> is there a table where it shows what version of bitbetter works with what version of bitwarden somewhere?

Unfortunately not. It's an unsupported solution. The best thing to do is to test in your lab, as anhnvme said.
