### ISSUE TITLE
Use in production environment

### ISSUE THREAD

**Issue by robina80** [jakeswenson/BitBetter#143]
Hi all,

Just curious, does anyone use bitbetter in a live production environment

Thanks,
Rob

**Comment by captainhook** [comment]
Yes, but I would not recommend it. Bitbetter is a patch with zero support. If something breaks, you have to hope someone in this tiny community can help.

**Comment by captainhook** [comment]
I would touch vaultwarden with a bargepole only because there has been no security audit. Your risk appetite may be different. Also be aware features are missing from vw.
