### ISSUE TITLE
can bitwarden disable bitbetter

### ISSUE THREAD

**Issue by robina80** [jakeswenson/BitBetter#144]
hi all,

bitbetter is awesome and thank you for the immense work on it, just wondering, is there anyway bitwarden can disable it so bitbetter stops working, just curious if they can put a stop to it

thanks,
rob

**Comment by h44z** [comment]
If they change their license check mechanism, the current method that BitBetter uses might break and self-generated licenses will not work any longer. But as long as the license checking system is open source, there will be a way to adopt BitBetter.
And also, if you do not update Bitwarden, it will work forever (however, keeping Bitwarden out of date is not recommended).
