### ISSUE TITLE
How do people handle "license has expired"?

### ISSUE THREAD

**Issue by Ayitaka** [jakeswenson/BitBetter#149]
I am curious as to how people handle instances where you receive an email informing you that an Org license has expired, before it is even due to expire. 

There are times when some change causes licenses to prematurely become invalid. After we apply whatever fix is required to resolve the initial change that caused them to be invalid, we can just regenerate the licenses. But I am curious, at that point, is there some way to return existing licenses to a valid state?

**Comment by captainhook** [comment]
I've had licenses active for nearly 3 years without any such issues through many, many upgrades. Unless you change your private key, I cannot see any reason why licenses should become invalid.
