### ISSUE TITLE
Invalid username or password

### ISSUE THREAD

**Issue by KCH0000** [jakeswenson/BitBetter#156]
I try update from 1.41 to latest versions. In my build, i use traefik for proxy bitwarden nginx.
After update to 2022.12.0  can`t login any users with error "Username or password is incorrect. Try again.

![изображение](https://user-images.githubusercontent.com/28162151/211614602-5ff50a7c-f367-4cda-9e17-788819a43645.png)
![изображение](https://user-images.githubusercontent.com/28162151/211614739-37d23959-1330-4740-915b-5d92f6045cd0.png)

**Comment by h44z** [comment]
this has nothing to do with BitBetter, maybe the Bitwarden update went wrong
