### ISSUE TITLE
Issue when running ./build.sh request denied

### ISSUE THREAD

**Issue by ryanmead22** [jakeswenson/BitBetter#158]
When running ./build.sh I get the following error:

Sending build context to Docker daemon  26.62kB
Step 1/7 : FROM mcr.microsoft.com/dotnet/sdk:6.0 as build
 ---> fb2953aaad51
Step 2/7 : WORKDIR /licenseGen
 ---> Using cache
 ---> 7b78dfe6eaef
Step 3/7 : COPY . /licenseGen
 ---> Using cache
 ---> 4a8eccd406ec
Step 4/7 : RUN set -e; set -x;  dotnet add package Newtonsoft.Json --version 13.0.1     && dotnet restore       && dotnet publish
 ---> Using cache
 ---> 006c97843b62
Step 5/7 : FROM bitbetter/api
pull access denied for bitbetter/api, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

I have tried logging in with my docker account (sudo docker login). This logs in fine, run the command again and still get the same issue. Any ideas?

Thanks, 
Ryan

**Comment by blindrain** [comment]
I get similar issue for Issue #163

**Comment by toni-1** [comment]
If "update-bitwarden.sh" asks for pruning the docker images use "No" (default).
