### ISSUE TITLE
Circle-ci Checkout Key

### ISSUE THREAD

**Issue by JeffAlyanak** [jakeswenson/BitBetter#16]
The circle-ci checkout key seems to be incorrect, causing all circle-ci tests to fail. I think @jakeswenson is probably the only one who can fix that.

**Comment by jakeswenson** [comment]
resolved the key issue, but build is failing because of a missing `.key` directory now.

**Comment by JeffAlyanak** [comment]
Which script is failing? We can just add the following:

```
[ -e .keys ] || mkdir .keys
```

That'll generate the directory if it doesn't exist.
