### ISSUE TITLE
mv: cannot move '/app/Core.dll' to a subdirectory of itself, '/app/Core.orig.dll'

### ISSUE THREAD

**Issue by fubman** [jakeswenson/BitBetter#160]
![Screenshot 2023-03-05 205528](https://user-images.githubusercontent.com/14334817/222982710-840b475a-f2d7-4035-9414-94edd36db5b4.png)

How to fix it? ./build.sh doesnt work

cant even start my old version 

![Screenshot 2023-03-05 212813](https://user-images.githubusercontent.com/14334817/222984210-357c27eb-aa55-4671-adb9-80bc18f53b19.png)

**Comment by psjamze** [comment]
i have the exact same issue: 

Pulling identity (bitbetter/identity:2023.7.0)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost.

**Comment by psjamze** [comment]
seems like the docker-compose.override.yml creates itself wrongly via the bitbetter builder. It still needs to be like in the readme: 

without the actually version attached 

> ![Screenshot 2023-03-05 205528](https://user-images.githubusercontent.com/14334817/222982710-840b475a-f2d7-4035-9414-94edd36db5b4.png)
> 
> How to fix it? ./build.sh doesnt work
> 
> cant even start my old version
> 
> ![Screenshot 2023-03-05 212813](https://user-images.githubusercontent.com/14334817/222984210-357c27eb-aa55-4671-adb9-80bc18f53b19.png)

**Comment by fubman** [comment]
Use a VM instead of an LXC than it’s working 😄
