### ISSUE TITLE
Unable to update to 2023.8.0

### ISSUE THREAD

**Issue by oliverjnash** [jakeswenson/BitBetter#167]
Hi there, 

The BitBetter upgrade script doesn't seem to be picking up the latest version of BW. I've re-cloned and rebuilt BitBetter but it's only picking up version 2023.7.2 rather than the latest (2023.8.1). 

Is this an issue you're aware of? 

Many thanks

**Comment by Ayitaka** [comment]
The most recent released version of [self-hosted](https://github.com/bitwarden/self-host) core is still 2023.7.2.

Bitwarden does not update self-hosted right away. They will test the latest release (2023.8.1) on their servers first for a week or so and then release it for self-hosted.

**Comment by oliverjnash** [comment]
Thanks @Ayitaka - will check again next week
