### ISSUE TITLE
Build issue (certificate related)

### ISSUE THREAD

**Issue by tam481** [jakeswenson/BitBetter#17]
Hello,
Where are we supposed to generate the self-signed certificate?

I noticed that the build.sh script copies a cert.cer from .keys directory to ./src/bitBetter/.keys but during the build it says 
_"mkdir: cannot create directory ‘./src/bitBetter/.keys’: File exists
cp: cannot stat '.keys/cert.cert': No such file or directory"_

That's because there is what looks like a corrupt cert file in ./src/bitBetter/.keys whereas the .keys directory at the root is empty and contains a text file that says that!

**Comment by JeffAlyanak** [comment]
In the current version you have to ensure that you generate the keys from within the `.keys` directory.

If you have already generated the keys elsewhere, simply move them inside the `.keys` directory.

**Comment by JeffAlyanak** [comment]
There is a new pull request ( https://github.com/jakeswenson/BitBetter/pull/14) that will likely be merged soon that automatically generates the keys in the correct location.

You can use that version now if you want to simplify the process.

**Comment by tam481** [comment]
That's great. I've managed to sort it out too. Definitely worth that enhancement for future releases.

**Comment by JeffAlyanak** [comment]
This feature has been merged into the mainline release now.
