### ISSUE TITLE
Version 2023.10.1 doesn't seem to work

### ISSUE THREAD

**Issue by akaJuliaan** [jakeswenson/BitBetter#171]
My Organization got suspended:
![image](https://github.com/jakeswenson/BitBetter/assets/54598714/ec1982e1-b019-4fd9-9980-71bf4854e7b6)

and when I try to upload a new certificate I always get "Invalid Certificate"

**Comment by emilsas** [comment]
Having same issue that @akaJuliaan reported.

**Comment by jjmmfi** [comment]
Haven’t yet tried to update but really into getting the passkeys support. Do you say all the paywalled features become unusable after update or does the whole password manager become unusable?

Thank you for sharing that!

**Comment by akaJuliaan** [comment]
all the paywalled features become unusable, but you can still access your passwords

**Comment by emilsas** [comment]
All feature become unusable for all users except to Owner role. Rest of organization doesn't have access to any item in the organization vault.

**Comment by emilsas** [comment]
> After I updated, I had to recreate the licenses for my orgs and after that, everything is working just fine

Recreate with the license generator same that we use for the first use?

**Comment by Ayitaka** [comment]
For what its worth, this is not just a BitBetter problem - it is a [general Bitwarden problem](https://www.reddit.com/r/Bitwarden/comments/17m2mtx/license_expired_anyone_else_get_an_email/) and [they are aware of the issue](https://www.reddit.com/r/Bitwarden/comments/17m2mtx/comment/k7ijnbp/?utm_source=share&utm_medium=web2x&context=3).

Recreating the license does work, but at least on mine it was suspended again the next morning when Bitwarden updated again. Hopefully they have resolved the issue with this latest update - we will have to see.
