### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by tam481** [jakeswenson/BitBetter#18]
Hello guys, 
There is paragraph in the documentation referring to modifying a run.sh file. I've downloaded the latest release of bitwarden and there doesn't seem to be a scripts directory.

You'll also want to edit the /path/to/bwdata/scripts/run.sh file. In the function restart() block, comment out the call to dockerComposePull.

Replace dockerComposePull
with #dockerComposePull

**Comment by JeffAlyanak** [comment]
Which directory did you install Bitwarden in?

You should have a `bwdata` directory after installing Bitwarden which contains your configs, scripts and data.

Are you able to identify where this `bwdata` directory is?

**Comment by tam481** [comment]
Thanks @JeffAlyanak I had basically assumed that I can't use the bitwarden.sh script provided by Bitwarden so downloaded the zip file version using the link on their website.

Might be worth updating the documentation to explain that.

Thanks

**Comment by JeffAlyanak** [comment]
Yeah, I can add to the prerequisites section of the Readme that Bitwarden needs to be installed.
