### ISSUE TITLE
Invalid license

### ISSUE THREAD

**Issue by hegedussz** [jakeswenson/BitBetter#184]
I use the master branch. When I trying update the license file I got this error: Invalid license.
I followed the instructions in the README.md

When I am using the old license file thats okay
When I am using the new license file thats not okay

**Comment by red3333** [comment]
I reinstalled bitwarden and bitbetter from scratch yesterday. My newly generated license was accepted by Bitwarden instance.

I can see 2 problems which could have happened to me (and maybe you ?) :

- the license key referenced in the license has to be valid
I don't know what it means actually, but I used one that works (I can receive and read mails on it) and that belong to a user (admin in my case) in Bitwarden.

- to my understanding, the certificates in BitBetter/.keys directory (they are generated automatically if they don't exist) have to be the same in the BitBetter containers (api and identity) and for the ./run.sh script (the certificates in the containers are used to verify the signature of the license file generated by ./run.sh)
If you just cloned the BitBetter repo and built a new license, you probably have to rebuild the BitBetter containers so they have the (new) certificates used to sign your new license.
