### ISSUE TITLE
licenseGen.sh in unified branch isn't working (.NET?)

### ISSUE THREAD

**Issue by Jonathan-Kortleven** [jakeswenson/BitBetter#188]
To reproduce: just pull the unified branch and try to generate a license. I think the unified branch is still behind on the .NET 8.0 fixes.

./licenseGen.sh 
You must install or update .NET to run this application.

App: /app/licenseGen.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '8.0.0' (x64)
.NET location: /usr/share/dotnet/

The following frameworks were found:
  6.0.27 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0.0&arch=x64&rid=debian.11-x64

**Comment by captainhook** [comment]
Please take a look at #180, @GieltjE something may have been missed.

**Comment by TheSp1der** [comment]
I can confirm this issue. I build my images via Jenkins and this is a new issue that just cropped up.

**Comment by GieltjE** [comment]
Made a new pull request, created my patch sets to quickly and missed half of it......

**Comment by Jonathan-Kortleven** [comment]
Thanks guys, tested & works like a charm!
