### ISSUE TITLE
Host to Host | Migration steps for BitBetter

### ISSUE THREAD

**Issue by mrventerj** [jakeswenson/BitBetter#197]
Hello, is there any guidance for migrating a BitBetter modified version of Bitwarden to a new host? ie - Reinstalling Bitwarden -> copying over the bwdata folder ect.

**Comment by mind12** [comment]
I have never tried it but I guess if you copy over the respective volume's (docker volume ls | grep bitwarden) directories from /var/lib/docker/volumes/ to the new server and set up the same docker and bitbetter environment you will be fine. Try it.
