### ISSUE TITLE
Ability to change "Business Name"

### ISSUE THREAD

**Issue by tam481** [jakeswenson/BitBetter#21]
Hi,
This is a very superficial and cosmetic request but would make things neater.

Would it be possible to change the hard coded "BitBetter" under business name to something custom like your family name etc?

**Comment by JeffAlyanak** [comment]
This is something I've already been looking at for a future release, but it might be a little while before you see it. Currently, my focus is on putting together a release that automates the setup and build process and includes an interactive mode for the license generator.

For now, you can edit the value in Program.cs (line 197) and rebuild the license generator to make it generate licenses with any name you'd like.

 https://github.com/jakeswenson/BitBetter/blob/15371c362c386d8c9413f584101fdf6d0e2d64f6/src/licenseGen/Program.cs#L197

**Comment by JeffAlyanak** [comment]
Hey @tam481, custom organization names have arrived!

The feature has been merged to the [master](https://github.com/jakeswenson/BitBetter/tree/master) branch with PR https://github.com/jakeswenson/BitBetter/pull/23. You'll find the details in the Readme.
