### ISSUE TITLE
iOS Login Issues

### ISSUE THREAD

**Issue by coryarobbins** [jakeswenson/BitBetter#210]
Hello,

With the lastest version of BitWarden/BitBetter and the iOS app, I get an "Error occurred" immediately after entering the email address for the login.  There was a post about this on the BitWarden forum that sounded similar but the issue was caused by using an external database.  I'm using the standard install, so I don't think this would be the issue. https://community.bitwarden.com/t/latest-ios-app-says-an-error-has-occurred-can-log-into-web-vault-fine/73985/13

I suppose I could still change the version numbers, but that seems... not like a great idea.

**Comment by captainhook** [comment]
It's not an issue with this tooling, I would suggest asking on the forum of following that suggested fix.
