### ISSUE TITLE
Unable after Update

### ISSUE THREAD

**Issue by DerKartdomi** [jakeswenson/BitBetter#218]
Hello, I once had the problem of updating Bitwarden. At the time I had to set a specific version for a few files. Now I don't remember what I changed. Il I found something in a file and changed it again but that doesn't help. When I do ./uodate-bitwarden.sh the following error occurs during setup

WARN[0000] /root/bwdata/docker/docker-compose.override.yml: the attribute `version`
is obsolete, it will be ignored, please remove it to avoid potential confusion
WARN[0000] /root/bwdata/docker/docker-compose.override.yml: the attribute `version`
is obsolete, it will be ignored, please remove it to avoid potential confusion
 [+] Pulling 11/11
 ✘ icons Error         context canceled                                        1.1s  ✘ nginx Error         context canceled                                        1.1s  ✘ mssql Error         context canceled                                        1.1s  ✘ attachments Error   context canceled                                        1.1s  ✘ events Error        context canceled                                        1.1s  ✘ notifications Error context canceled                                        1.1s  ✘ web Error           context canceled                                        1.1s  ✘ sso Error           context canceled                                        1.1s  ✘ api Error           pull access denied for bitbetter/api, rep...            1.1s  ✘ identity Error      context canceled                                        1.1s  ✘ admin Error         context canceled                                        1.1s Error response from daemon: pull access denied for bitbetter/api, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Pruning Docker images without at least one container associated to them...
WARNING! This will remove all images without at least one c

**Comment by cfoellmann** [comment]
thats in the docker-compose.yml

have a look in any yml files to remove `version: xxx`

**Comment by vdmchkv** [comment]
The issue you are referring to may be related to how Docker Compose works. It attempts to download the image for bitbetter/identity or bitbetter/api from the Docker repository. However, these images do not exist there, and therefore, the pull operation fails. The solution is straightforward: you can add the following...
```
pull_policy: never
``` 
...to the docker-compose.override.yml file (located in .../bwdata/docker/) after the image declaration. Then, you should be able to start Bitwarden, as Docker Compose will use the local image instead.

You can also verify that the local images are present by running **_docker image list_** command. You should see **bitbetter/api** and **bitbetter/identity** listed, along with the corresponding versions specified in the docker-compose.override.yml.

**Comment by h44z** [comment]
should be fixed by #219
