### ISSUE TITLE
Error in the documentation

### ISSUE THREAD

**Issue by DB-CL** [jakeswenson/BitBetter#24]
Hi, 

I spotted a tiny little error in the documentation

You should replace 
`git clone https://github.com/online-stuff/BitBetter.git`
by 
`git clone https://github.com/jakeswenson/BitBetter.git`

**Comment by JeffAlyanak** [comment]
Thanks @DB-CL, another contributor who had forked the repo had made an edit in the past that nobody had noticed until now.

**Comment by JeffAlyanak** [comment]
Typo fix (https://github.com/jakeswenson/BitBetter/pull/23/commits/19d3949b9d431adbe6a6c1ea904fa23e722503e4) has been merged to [master](https://github.com/jakeswenson/BitBetter/tree/master) branch in PR https://github.com/jakeswenson/BitBetter/pull/23.
