### ISSUE TITLE
Same as #26

### ISSUE THREAD

**Issue by johnczer** [jakeswenson/BitBetter#28]
Does this work on the latest version of bitwarden? I noticed that your screenshot shows an older version in docker. I've tried this in the latest version of bw and I get the invalid license error as well. Just curious-thanks

**Comment by JeffAlyanak** [comment]
Hi @johnczer, Issue #26 was solved by following the instructions in the correct order. Are you certain that you've followed the instructions correctly?

**Comment by johnczer** [comment]
Hi Jeff, I believe I did as I have this working on the same version you show in your screenshot but not much success on the latest version. I will run through these steps again. Do I replace the certs each time?  I was thinking it has something to do with the certs but not certain. Thanks

**Comment by JeffAlyanak** [comment]
What do you get as the output of `docker ps`?

**Comment by johnczer** [comment]
When I ran docker ps it showed what was in your screenshot but just the new version of BW. I’ll have to start another VM and I’ll test it again and send you a Ss. I rolled it back to the version yours showed which does work. Thanks for helping with this;)

**Comment by johnczer** [comment]
Here is what I currently get on the machine I am running now where everything works:
CONTAINER ID        IMAGE                            COMMAND             CREATED             STATUS              PORTS                                                 NAMES
167e26593ed5        portainer/portainer              "/portainer"        2 days ago          Up 8 seconds        0.0.0.0:9000->9000/tcp                                portainer
ff9eb8fdf7a9        bitwarden/icons:1.30.0           "/entrypoint.sh"    12 days ago         Up 4 seconds        5000/tcp                                              bitwarden-icons
8cc8d5659fe9        bitwarden/admin:1.30.0           "/entrypoint.sh"    12 days ago         Up 6 seconds        5000/tcp                                              bitwarden-admin
a7d35cebc44f        bitwarden/web:2.9.0              "/entrypoint.sh"    12 days ago         Up 3 seconds        5000/tcp                                              bitwarden-web
3a34e11fed91        bitwarden/notifications:1.30.0   "/entrypoint.sh"    12 days ago         Up 8 seconds        5000/tcp                                              bitwarden-notifications
9deab67290e0        bitwarden/mssql:1.30.0           "/entrypoint.sh"    12 days ago         Up 5 seconds        1433/tcp                                              bitwarden-mssql
2f88b17fe98a        bitwarden/nginx:1.30.0           "/entrypoint.sh"    12 days ago         Up 7 seconds        80/tcp, 0.0.0.0:80->8080/tcp, 0.0.0.0:443->8443/tcp   bitwarden-nginx
7c7b99b17c97        bitbetter/api:latest             "/entrypoint.sh"    12 days ago         Up 6 seconds        5000/tcp                                              bitwarden-api
750d1418a4aa        bitwarden/identity:1.30.0        "/entrypoint.sh"    12 days ago         Up 6 seconds        5000/tcp                                              bitwarden-identity
ff24b07434f8        bitwarden/attachments:1.30.0     "/entrypoint.sh"    12 days ago         Up 6 seconds        5000/tcp                                              bitwarden-attachments
I was going to try this on Server latest: 1.30.4/Web latest: 2.10.1 unless you don't think it will work.

**Comment by JeffAlyanak** [comment]
Which screenshot are you referring to? There are no screenshots in the current repository.

Also, it doesn't appear like the bitbetter/identity image is set up correctly. Are you sure built and added that correctly to `docker-compose.yml`?

**Comment by JeffAlyanak** [comment]
@johnczer  Just to confirm, you're using the latest version (https://github.com/jakeswenson/BitBetter/commit/5d01d3c661a9317a74d97243e4f95e5f36f9761e)?

What output do you get when you run the main `./build.sh` command? Can you post that here inside of a code tag?

**Comment by johnczer** [comment]
Hey Jeff when I get back to my computer I’ll get you this info. Thank you

**Comment by johnczer** [comment]
This was the screen shot or rather result of your docket ps results I was referring to https://github.com/jakeswenson/BitBetter/issues/26#issuecomment-498403948

**Comment by JeffAlyanak** [comment]
> This was the screen shot or rather result of your docket ps results I was referring to [#26 (comment)](https://github.com/jakeswenson/BitBetter/issues/26#issuecomment-498403948)

I see. You'll notice that your output and the example output I posted in that comment differ in more than just version numbers, though; in your example you can see that it is running `bitwarden/identity:1.xx.x` rather than `bitbetter/identity:latest`

**Comment by johnczer** [comment]
Yes, I do see that and I am not sure how I missed that. Curious that things seemed to be working with this version. But this would certainly explain why going forward is a problem. I must learn again to read..hahaha
So...in trying to fix this faux pas I am forced to revisit some past mistakes. I started with the steps again from the beginning and got to the part where I restart bw (just before manually generating the certs) and I get this:
Creating network "docker_default" with the default driver
Pulling identity (bitbetter/identity:latest)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling identity (bitbetter/identity:latest)...
ERROR: pull access denied for bitbetter/identity, repository does not exist or may require 'docker login'

So this leads me to questions about the following, bear in mind I am still learning when it comes to Linux.
- I have bitbetter installed at home/bitwarden/bitbetter
- I have bitwarden installed at opt/bitwarden/bwdata
I think I followed one of many scripts in the beginning, hence the "opt" directory install location; does bitbetter need to be in the same folder under bwdata?
If my certs are already there from a previous build do I still need to replace these or do I just skip this section?

**Comment by JeffAlyanak** [comment]
> Continue with the new image? [yN]y
> Pulling identity (bitbetter/identity:latest)...
> ERROR: pull access denied for bitbetter/identity, repository does not exist or may require 'docker login'

This is generally a sign that you have not successfully built the bitbetter/identity container image. Are you certain that the `./build.sh` script is successfully building the two images?
 
> I think I followed one of many scripts in the beginning, hence the "opt" directory install location; does bitbetter need to be in the same folder under bwdata?

BitBetter does not need to be installed in any particular directory. What BitBetter does is modify and build docker images, so it doesn't really matter where it is.

> If my certs are already there from a previous build do I still need to replace these or do I just skip this section?

The main `./build.sh` script will only auto-regenerate certs if you don't already have them in the `./.keys` directory. If you choose to manually re-generate them then you can, but you'll have to regenerate all your licenses.

**Comment by johnczer** [comment]
I am getting closer:)  The step that I've not had any problems but do now...generating the licenses.  Error I get:
Unable to find image 'bitbetter/licensegen:latest' locally
docker: Error response from daemon: pull access denied for bitbetter/licensegen, repository does not exist or may require 'docker login'.
See 'docker run --help'.

**Comment by JeffAlyanak** [comment]
> Unable to find image 'bitbetter/licensegen:latest' locally
> docker: Error response from daemon: pull access denied for bitbetter/licensegen, repository does not exist or may require 'docker login'.

Just as before, this message means that you do not have that docker image. Have you successfully built the license generator? What output do you get when building the license generator?

**Comment by johnczer** [comment]
Restore completed in 85.75 ms for /home/bitwarden/BitBetter/src/bitBetter/bitBetter.csproj.
Microsoft (R) Build Engine version 16.1.76+g14b0a930a7 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 91.42 ms for /home/bitwarden/BitBetter/src/bitBetter/bitBetter.csproj.
  bitBetter -> /home/bitwarden/BitBetter/src/bitBetter/bin/Debug/netcoreapp2.0/bitBetter.dll
  bitBetter -> /home/bitwarden/BitBetter/src/bitBetter/bin/Debug/netcoreapp2.0/publish/
Sending build context to Docker daemon  1.219MB
Step 1/4 : FROM bitwarden/api
latest: Pulling from bitwarden/api
Digest: sha256:5f2eb5f6974673bc6f186093ba7706e98ccc9b03a6ac5f5fb96983c699e6ecb5
Status: Image is up to date for bitwarden/api:latest
 ---> 93f9d5912bbd
Step 2/4 : COPY bin/Debug/netcoreapp2.0/publish/* /bitBetter/
 ---> Using cache
 ---> 430526ac17bd
Step 3/4 : COPY ./.keys/cert.cert /newLicensing.cer
 ---> Using cache
 ---> c9992fcaeeb9
Step 4/4 : RUN dotnet /bitBetter/bitBetter.dll &&     echo "modified dll" &&     mv /app/Core.dll /app/Core.orig.dll &&     mv /app/modified.dll /app/Core.dll &&     echo "replaced dll" &&     rm -rf /bitBetter && rm -rf /newLicensing.cer &&     echo "cleaned up"
 ---> Using cache
 ---> 9aa566aa6ccf
Successfully built 9aa566aa6ccf
Successfully tagged bitbetter/api:latest
Sending build context to Docker daemon  1.219MB
Step 1/4 : FROM bitwarden/identity
latest: Pulling from bitwarden/identity
Digest: sha256:91e48db10e87dbc7c6efe7679ea4c104f18733262683b21f82122e52f2e5949b
Status: Image is up to date for bitwarden/identity:latest
 ---> a56b8df942de
Step 2/4 : COPY bin/Debug/netcoreapp2.0/publish/* /bitBetter/
 ---> Using cache
 ---> 850bb2adce06
Step 3/4 : COPY ./.keys/cert.cert /newLicensing.cer
 ---> Using cache
 ---> 46a5f891ddf2
Step 4/4 : RUN dotnet /bitBetter/bitBetter.dll &&     echo "modified dll" &&     mv /app/Core.dll /app/Core.orig.dll &&     mv /app/modified.dll /app/Core.dll &&     echo "replaced dll" &&     rm -rf /bitBetter && rm -rf /newLicensing.cer &&     echo "cleaned up"
 ---> Using cache
 ---> c1accdaaa005
Successfully built c1accdaaa005
Successfully tagged bitbetter/identity:latest

**Comment by johnczer** [comment]
Jeff, I got this to work.  Looking at my old notes I ran these in this order:
This first:  ./build.sh from BitBetter dir
This second: ./build.sh from licenseGen dir
I know my reading skills aren't reliable but I don't see that in your instructions to run ./build a second time. Not sure if this is right but things seem to be working...
I really appreciate the help.

**Comment by JeffAlyanak** [comment]
Glad to hear that you've gotten it working.

> I know my reading skills aren't reliable but I don't see that in your instructions to run ./build a second time.

It is already in the instructions in the [Generating Signed Licenses](https://github.com/jakeswenson/BitBetter#generating-signed-licenses) section.
