### ISSUE TITLE
Unable to find image 'bitbetter/licensegen:latest' locally

### ISSUE THREAD

**Issue by rinosantilli** [jakeswenson/BitBetter#29]
./src/licenseGen/run.sh interactive
Unable to find image 'bitbetter/licensegen:latest' locally
docker: Error response from daemon: pull access denied for bitbetter/licensegen, repository does not exist or may require 'docker login'.
See 'docker run --help'.

how do I solve this?

I did all the steps, but can't generale a license.

Regards

**Comment by JeffAlyanak** [comment]
Hi @rinosantilli, this message means that you have not successfully built the license generator.

Can you include the output from the license generator build script in code tags below?

**Comment by Ivan1874** [comment]
I think that you didn't understand the instructions 
Run cd src/licenseGen
And then ./build.sh
then try ./run.sh interactive again

**Comment by JeffAlyanak** [comment]
Closing this for now, as there doesn't seem to be any evidence that this is a real issue.
