### ISSUE TITLE
Invalid license or not supported version

### ISSUE THREAD

**Issue by wbebw** [jakeswenson/BitBetter#31]
Hi. First of all, thanks for your work.

Unfortunately, i have faced with problem - i have done all actions according to instruction. Compose was changed, identity, api succesfully builded - i saw other issues and double checked it. I succesful run licenseGen/run.sh, provided all information including installation_id from env
i got generated license file.

But this file is not accepted by my self-hosted application. I'm trying to get premium and upload license json - it says that "version 4 is not supported", or if i'm truing to make organization, it says "invalid license".

I am stuck.

**Comment by JeffAlyanak** [comment]
Hey @wbebw , are you able to **confirm the version of bitwarden** that you're using? If you run `docker ps` you should see something like:


```bash
e94472a6d66b        bitwarden/mssql:1.29.0           "/entrypoint.sh"         22 hours ago        Up 13 hours             1433/tcp                                   bitwarden-mssql
5a0a7ce8d8b2        bitbetter/identity:latest        "/entrypoint.sh"         22 hours ago        Up 13 hours             5000/tcp                                   bitwarden-identity
9405a9e1fcd0        bitwarden/icons:1.29.0           "/entrypoint.sh"         22 hours ago        Up 13 hours             5000/tcp                                   bitwarden-icons
2a16b4d6ced9        bitwarden/nginx:1.29.0           "/entrypoint.sh"         22 hours ago        Up 13 hours             80/tcp, 8080/tcp, 0.0.0.0:6001->8443/tcp   bitwarden-nginx
8cd3a817c971        bitwarden/notifications:1.29.0   "/entrypoint.sh"         22 hours ago        Up 13 hours             5000/tcp                                   bitwarden-notifications
721b1cd8aca4        bitwarden/attachments:1.29.0     "/entrypoint.sh"         22 hours ago        Up 13 hours             5000/tcp                                   bitwarden-attachments
329b3484441b        bitwarden/admin:1.29.0           "/entrypoint.sh"         22 hours ago        Up 13 hours             5000/tcp                                   bitwarden-admin
329b3484441b        bitwarden/web:2.8.0              "/entrypoint.sh"         22 hours ago        Up 13 hours             5000/tcp                                   bitwarden-web
329b3484441b        bitbetter/api:latest             "/entrypoint.sh"         22 hours ago        Up 13 hours             5000/tcp                                   bitwarden-api
```

**Comment by wbebw** [comment]
Thanks for fast answer, sure, here it is:
![изображение](https://user-images.githubusercontent.com/53523506/62219845-b5ae5900-b3b7-11e9-97c7-d1b769890317.png)

**Comment by JeffAlyanak** [comment]
@wbebw I haven't tested with that particular version of Bitwarden yet since it just came out 4 days ago.

It might take me a few days before I can look into version 1.31.0. If you want to get up and running right away, you can just install bitwarden 1.29.0 and then use BitBetter on top of that version instead.

**Comment by wbebw** [comment]
wow, really, i missed it. thank you!
i will try to downgrade bitwarden, but newer version is intersted too, good luck with it!
thanks again for your time

**Comment by wbebw** [comment]
Hi, i have downgrade to 1.29, but still no luck, the error the same. Here it is:
![изображение](https://user-images.githubusercontent.com/53523506/62276329-79790800-b44c-11e9-9839-eea8e2b5ad61.png)
![изображение](https://user-images.githubusercontent.com/53523506/62276356-87c72400-b44c-11e9-93ca-ef44d408084c.png)
![изображение](https://user-images.githubusercontent.com/53523506/62276390-9a415d80-b44c-11e9-8c4a-45ed15efb338.png)

**Comment by aveao** [comment]
CNR on 1.31.1

![](https://elixi.re/i/suhbod5r.png)

![](https://elixi.re/i/paadc6k6.png)

**Comment by wbebw** [comment]
@aveao sooo... as i see, you have done it successfully, but there is no info - how.

**Comment by aveao** [comment]
@wbebw I followed readme, it worked for me out of the box.

**Comment by JeffAlyanak** [comment]
@wbebw Unfortunately, just like @aveao I am unable to replicate this issue. What version of docker and docker-compose are you using? Can you go through the exact steps that you are taking to get that error?

**Comment by screed59** [comment]
@JeffAlyanak sorry,had to change account, couldnt confirm email. here is versions. all from official repo. Trying again grom very beginnig, probably, @aveao was right and i am blind ;)

sec@ubuntusec:~$ sudo docker version
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.1
 Git commit:        2d0083d
 Built:             Wed Jul  3 12:13:59 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.1
  Git commit:       2d0083d
  Built:            Mon Jul  1 19:31:12 2019
  OS/Arch:          linux/amd64
  Experimental:     false

 
sec@ubuntusec:~$ sudo docker-compose version
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.15rc1
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018

**Comment by screed59** [comment]
current state:
![изображение](https://user-images.githubusercontent.com/50068109/62294466-a1c82d00-b473-11e9-84b8-92d3b4a3b005.png)

build.sh:
Successfully built 00fced09ab14
Successfully tagged bitbetter/api:latest
Successfully built b0e4e13417a4
Successfully tagged bitbetter/identity:latest

config.yml:
api:
    image: bitbetter/api
  identity:
    image: bitbetter/identity

script:
function restart() {
    dockerComposeDown
    #dockerComposePull

build licenseGen:
Successfully built cba228b1edae
Successfully tagged bitbetter/licensegen:latest

running sec@ubuntusec:~/BitBetter$ sudo ./src/licenseGen/run.sh interactive
choose [o]rg license
fill info and paste installation ID (i got it from https://bitwarden.com/host/ after set email, which also used at installig bitwarden itself according to its instruction - https://help.bitwarden.com/article/install-on-premise/)

i got licence json on terminal, i save it to file

**Comment by screed59** [comment]
now i restarting with bitbetter
![изображение](https://user-images.githubusercontent.com/50068109/62295208-3a12e180-b475-11e9-99c4-cb67c5c9210f.png)
i confirm my email in bitwarden and go to premium panel, upload the generated json

**Comment by screed59** [comment]
and got this 
![изображение](https://user-images.githubusercontent.com/50068109/62295340-7a725f80-b475-11e9-9e4f-7d2127e7114d.png)

so, am i missing something, @JeffAlyanak ?

**Comment by JeffAlyanak** [comment]
Is this from a fresh install of Bitwarden or one that you have been using for a while that's been upgraded from older versions?

**Comment by screed59** [comment]
it's fresh virtual machine, so yes, it is brand new

**Comment by screed59** [comment]
okay, that was it. no premium, as said aveao.
i managed it by settings->new organization->upload that file again and it was accepted.

before it i login to admin panel, make sure that installID is the same (ok) and logout. after that i tried again to get premium, get error (version 4 is not supported again), and only after that organization panel accept license file

**Comment by JeffAlyanak** [comment]
I have no idea what you changed but it sounds like you got it working?

**Comment by screed59** [comment]
indeed, i really did that 10 times and no luck... so yes, at this time i am able to create organization ;) thanks again, it is working
