### ISSUE TITLE
Certificate Generation

### ISSUE THREAD

**Issue by corexo** [jakeswenson/BitBetter#32]
Hello i get the message

root@bitwarden:/home/bitwarden# ./src/licenseGen/run.sh /cert.pfx interactive
Cant find certificate at: /cert.pfx

Usage:  interactive

**Comment by corexo** [comment]
https://dotnet.microsoft.com/download/linux-package-manager/ubuntu16-04/sdk-current
was missing and i had to put the full path /home/bitwarden/src/licenseGen/run.sh /home/bitwarden/cert.pfx interactive

problem solved

**Comment by JeffAlyanak** [comment]
Hey @corexo, the absolute path to the cert is definitely required but you should not need to install any dotnet packages on your host as the actual compilation of the dotnet code is done inside a container.
