### ISSUE TITLE
Error cant find bitbetter/api

### ISSUE THREAD

**Issue by robina80** [jakeswenson/BitBetter#34]
hi all,

i have installed bitwarden and its great but now i want to set up organisations

i have come accross this

https://github.com/jakeswenson/BitBetter

but im struggling to do it, i am running this command below in my "/bitwarden/bwdata/"

git clone https://github.com/jakeswenson/BitBetter.git 

its made it here " /bitwarden/bwdata/BitBetter"

then i run the script

./build.sh 

then i edit my file like it says ie

Replace image: bitwarden/api:x.xx.x
with image: bitbetter/api

Replace image: bitwarden/identity:x.xx.x
with image: bitbetter/identity

but when i restart bitwarden it throughs an error -
Trying to pull repository docker.io/bitbetter/api ...

ERROR: repository docker.io/bitbetter/api not found: does not exist or no pull access

so obviously i havnt saved it in the right directory
can anyone help me out please

thanks,

rob

**Comment by JeffAlyanak** [comment]
The error you are getting occurs when the bitbetter/api image has not been built.

Are you certain that you are building it successfully?

**Comment by robina80** [comment]
Hi Jeff, thanks for your reply.

I run the command below in the bitwarden/bwdata directory 

git clone https://github.com/jakeswenson/BitBetter.git

its made it here " /bitwarden/bwdata/BitBetter"

Then i CD to the directory above as the root build script is there and then I run it like below 

./build.sh

Also I've logged in as root

I have no idea if it's building it correctly, how do I know

Many thanks,
Rob

**Comment by robina80** [comment]
i have re-run the build.sh script and i still get the error

i have seen this is a microsoft.net package... is this ok for a centos 7.7 vm installation?

i even deleted the BitBetter dir and run the git command again but still no joy

**Comment by robina80** [comment]
issue resolved...

i installed a ubuntu 18.04 server vm

when i ran the build script it went through alot more stages

also when i edited the config files it gave me no errors

thanks so much for your help

rob
