### ISSUE TITLE
How many users can i have in organisations

### ISSUE THREAD

**Issue by robina80** [jakeswenson/BitBetter#36]
Hi all,

How many users can I add to an organisation, is it unlimited?

Thanks,
rob

**Comment by JeffAlyanak** [comment]
Hi @robina80, the max number of users in an organization is set by the [`Seats` value](https://github.com/jakeswenson/BitBetter/blob/3e44d7347bb0097b9930acee3a7850d0c13dc7f0/src/licenseGen/Program.cs#L360) in the license. We currently have it hard-coded to 32767.
