### ISSUE TITLE
how to stop accidental deletion from organisation from personnal vault

### ISSUE THREAD

**Issue by robina80** [jakeswenson/BitBetter#38]
hi all,

i have noticed when i create an organisation and put stuff in the vault, it saves the stuff to my own personnal vault aswell

is there anyway of stopping this from happening as a user could delete stuff in there perssonal vault and it will replicate the deletetion to the organisation aswell

thanks,
rob

**Comment by JeffAlyanak** [comment]
Hey @robina80,

When creating a new credential, or when editing existing credentials, you can choose to share it with any organizations that you are a member of. 

Once shared, it cannot be unshared from the organization. Organization members without editing permissions will then be unable to delete it.

Unfortunately, this is not within the scope of our license generator, so it's not functionality that we can address, really.
