### ISSUE TITLE
enforcing 2FA for all users

### ISSUE THREAD

**Issue by robina80** [jakeswenson/BitBetter#40]
hi all,

i have read you cant enforce 2FA on normal bitwarden installations as its greyed out but as i have installed bitbetter i now have the option as i imagine i have the enterprise one or custom version?

is this possible to do now?

thanks,
rob

**Comment by sutidor** [comment]
Hi Rob,
go to #/settings/two-factor and set it up. I prefer Authy to google authenticator, check it out if you like.

cheers

**Comment by robina80** [comment]
is this user based or a global setting?

**Comment by robina80** [comment]
i can now see duo 2FA in the organisations page settings but now i need to create a duo account

i have read the free one can only do up to 10 users?

**Comment by sutidor** [comment]
BitBetter does not change any of the Bitwarden functionality. It will just unlock it.

On organisations you can use Duo, for users you can use authy, yubikey, email and another one.

**Comment by JeffAlyanak** [comment]
As @sutidor mentioned, BitBetter does not alter the functionality of Bitwarden and so this is outside the scope our our issues list.
