### ISSUE TITLE
manual docker installation - cant find scripts dir

### ISSUE THREAD

**Issue by robina80** [jakeswenson/BitBetter#41]
hi all,

im trying a manual installation of bitwarden here (right at the bottom of the how to)

https://help.bitwarden.com/article/install-on-premise/

but when i do a ls of bwdata i cant find the scripts dir

ls /bwdata/
BitBetter  ca-certificates  core  docker  env  identity  letsencrypt  logs  mssql  nginx  ssl  web

thanks,
rob

**Comment by robina80** [comment]
ok it looks like i need to install nginx?

**Comment by JeffAlyanak** [comment]
@robina80 BitBetter is not the same thing as Bitwarden. As I've mentioned to you a few times now, Issues relating to Bitwarden should be directed to the Bitwarden repositories, not here.
