### ISSUE TITLE
does bitbetter work offline

### ISSUE THREAD

**Issue by robina80** [jakeswenson/BitBetter#42]
hi all,

made bitwarden again this time doing it via the "Manual Docker Installations" so it doesnt need the internet to pull down the docker containers all the time

but if i make this an offline server will bitbetter still work or do i manually need to pull/save/load the bitbetter docker container?

many thanks,
rob

**Comment by robina80** [comment]
smashed it

i had to run this for the docker containers to take affect

docker-compose -f /bitwarden/bwdata/docker/docker-compose.yml up -d

the i saw it "recreating bitwarden identity and api"

now when i do a "docker ps"

i can now see the new containers

**Comment by tukusejssirs** [comment]
@robina80: Could you post a guide with all necessary commands? I am thinking about using BitBetter offline on a single computer.

Thank you in adnvace. :)

**Comment by JeffAlyanak** [comment]
@tukusejssirs You'll need a network connection when building the containers required for the build process, so unless you already have those containers locally you won't be able to go through the BitBetter process totally offline.

**Comment by tukusejssirs** [comment]
@JeffAlyanak, yes, I understand that the installation cannot be done offline. All I’d like to have a server that would run Bitwarden/BitBetter server that would be accessible only from that server.

That is: I want to _run_ the BW/BB offline, not install/build/deploy it offline. :)

**Comment by JeffAlyanak** [comment]
Then yes, that is totally possible.

**Comment by robina80** [comment]
here you go - 

first when your bitwarden server is online run this command to pull/save/load all the dockers - 

#!/bin/bash

mkdir /dockers

cd /dockers

docker pull bitwarden/web
docker save bitwarden/web:latest > bitwarden.web:latest.tar
docker load < bitwarden.web:latest.tar
docker pull bitwarden/mssql
docker save bitwarden/mssql:latest > bitwarden.mssql:latest.tar
docker load < bitwarden.mssql:latest.tar
docker pull bitwarden/nginx
docker save bitwarden/nginx:latest > bitwarden.nginx:latest.tar
docker load < bitwarden.nginx:latest.tar
docker pull bitwarden/admin
docker save bitwarden/admin:latest > bitwarden.admin:latest.tar
docker load < bitwarden.admin:latest.tar
docker pull bitwarden/events
docker save bitwarden/events:latest > bitwarden.events:latest.tar
docker load < bitwarden.events:latest.tar
docker pull bitwarden/notifications
docker save bitwarden/notifications:latest > bitwarden.notifications:latest.tar
docker load < bitwarden.notifications:latest.tar
docker pull bitwarden/icons
docker save bitwarden/icons:latest > bitwarden.icons:latest.tar
docker load < bitwarden.icons:latest.tar
docker pull bitwarden/attachments 
docker save bitwarden/attachments:latest > bitwarden.attachments:latest.tar
docker load < bitwarden.attachments:latest.tar
docker pull bitwarden/identity
docker save bitwarden/identity:latest > bitwarden.identity:latest.tar
docker load < bitwarden.identity:latest.tar
docker pull bitwarden/api
docker save bitwarden/api:latest > bitwarden.api:latest.tar
docker load < bitwarden.api:latest.tar
docker pull bitwarden/setup
docker save bitwarden/setup:latest > bitwarden.setup:latest.tar
docker load < bitwarden.setup:latest.tar
docker pull bitwarden/server
docker save bitwarden/server:latest > bitwarden.server:latest.tar
docker load < bitwarden.server:latest.tar

then read the "Manual Docker Installations" here - 

https://help.bitwarden.com/article/install-on-premise/

now you can take your server offline

let me know if you need anymore help

rob

**Comment by tukusejssirs** [comment]
Thank you @robina80. ;)
