### ISSUE TITLE
[WIP]: `README.md` improvements

### ISSUE THREAD

**Issue by tukusejssirs** [jakeswenson/BitBetter#43]
## BitBetter README.md improvements

We should probably move it from README.md. I suggest to create either GitHub Wiki or files in the brackets bellow in the repo root or in the `[repo_root]/docs` folder. Then, the `README.md` should contain only the general information about the repository/project/program.

### Add full documentation
- How to install (`INSTALL.md`; cf [my comment](https://github.com/jakeswenson/BitBetter/issues/6#issuecomment-551655909) in #6)
  - List the dependencies with instructions how to install them (at least a link to a guide)
- How to run (`RUN.md`)
- How to upgrade (`UPGRADE.md`)
- How to uninstall (`UNINSTALL.md`)
- FAQs (`FAQ.md`)

### Improve wording:
- Replace _Pre-requisites_ with _Dependencies_

### Questions:
- What is _IL_ in _janky IL magic_? We should not use shortcuts like this in the docs.

**Comment by JeffAlyanak** [comment]
Hey @tukusejssirs, I definitely agree with the change to the word dependencies but I don't think it's within the scope of our docs to get into the details of installing those dependencies and, frankly, there are many differences in how those dependencies would be installed based on your OS and environment.

Regarding your comments, it's again outside the scope of our docs to get into details on how to use docker but I wouldn't recommend using root. As a general rule for all *nix software; never use root unless absolutely necessary.

As for the instructions for installation, running, uninstallation; given that the software is containerized, there isn't any traditional installation or uninstallation and the instructions that you see in the current docs really are all there are.

Is there a particular question regarding the instructions that could be clarified?

**Comment by tukusejssirs** [comment]
I don’t we _must_ list all possible variations of dependencies installation. I think that listing of the package names is sufficient (although the package names might be different in different package managers, so we should list the packages names for the main package managers if they differ: `apt`, `yum`/`dnf`, `pacman`, `zypper`, `emerge`).

But I think the `docker` is a special case. Again: I don’t say we should provide the instructions itself, but the list to the Docker Docs. I am new to the Docker and today I had troubles installing it (I have installed the `docker` package from `yum` repos, but I had to install the package from Docker repo to make BitBetter `./build.sh` work).

Also, if someone reports an issue (like different package name or additional steps), we should _at least_ add some notes to the guides and list to the solution/workaround.

I understand that `root` should be avoided unless necessary. But I could not run `./build.sh` without `sudo` on CentOS 7, here is the output (the `docker` service is active and running):

```bash
Generating a 4096 bit RSA private key
...............++
.....................++
writing new private key to '/home/ts/a/home/ts/bb_3/.keys/key.pem'
-----
build.sh  README.md  src
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/build?buildargs=%7B%22BITWARDEN_TAG%22%3A%22bitwarden%2Fapi%22%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=aw266a345p50pkzmvqjjnsq6r&shmsize=0&t=bitbetter%2Fapi&target=&ulimits=null&version=1: dial unix /var/run/docker.sock: connect: permission denied
ERRO[0000] failed to dial gRPC: cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: dial unix /var/run/docker.sock: connect: permission denied 
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/build?buildargs=%7B%22BITWARDEN_TAG%22%3A%22bitwarden%2Fidentity%22%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=qmf9hoby2nxq0b55cvf3bvp8q&shmsize=0&t=bitbetter%2Fidentity&target=&ulimits=null&version=1: dial unix /var/run/docker.sock: connect: permission denied
```

> Is there a particular question regarding the instructions that could be clarified?
Partially, you have answered this [here](https://github.com/jakeswenson/BitBetter/issues/6#issuecomment-551842354) when you provided me told me to install [Bitwarden server](Is there a particular question regarding the instructions that could be clarified?) first. Although you somewhat mention this in the `README.md`, I think you aren’t clear enough, that’s why I suggest to improve the installation guide. For first-time users (like myself), it is not enough. That link should be in the `README.md` (or `INSTALL.md`) withing the installation guide.

**Comment by JeffAlyanak** [comment]
While I'm happy to look into putting specific version number requirements into the dependency section, I don't think it's a good idea to include package names. It would become very cluttered and I don't think I've ever seen documentation for cross-platform software include package names.

I understand your point of view regarding docker, but I disagree that our docs should include guidance on installing or setting up docker. Again, there are just too many different configurations to cover and the docker docs are already quite complete and supplemented very well by countless community-created tutorials and youtube videos.

Regarding people reporting issues, if there are any issues in the install process I'd much prefer to solve that in the software itself rather than adding workarounds to the docs but if you can point out any issues that can't be solved easily I would add that to the docs until such a time that I could solve it properly.

On the issue of root, it simply sounds like you haven't given your user permission to use docker. Again, this is covered very fully in Docker's documentation and in tutorials. I'd highly recommend that you dive into that a bit before deploying software with Docker.

While it is already stated in the first line of the doc, I can certainly improve the description of the software to make it more clear that as a modification of Bitwarden, you'll need to first have a working installation of Bitwarden set up. That's a good suggestion.

**Comment by tukusejssirs** [comment]
So, if I got it right:

1. Install Bitwarden/BitBetter dependencies.

```bash
### Install docker
### src: https://docs.docker.com/install/linux/docker-ce/centos/

# Remove previous versions of these packages
sudo yum -y remove docker docker-client docker-client-latest docker-common \
  docker-latest docker-latest-logrotate docker-logrotate docker-engine

# Install required packages
sudo yum -y install yum-utils device-mapper-persistent-data lvm2

# Add the Docker stable repository
sudo yum-config-manager \
  --add-repo https://download.docker.com/linux/centos/docker-ce.repo


# Install the latest version of Docker Engine CE and `containerd`version:
sudo yum -y install docker-ce docker-ce-cli containerd.io

# Enable and start the `docker` service
sudo systemctl enable docker
sudo systemctl start docker

### Install other dependencies

# Install `openssl`
sudo yum -y install openssl
```

2. Install [Bitwarden server](https://help.bitwarden.com/article/install-on-premise/).

```bash
curl -Lso bitwarden.sh https://go.btwrdn.co/bw-sh && chmod +x bitwarden.sh
./bitwarden.sh install
./bitwarden.sh start
```

3. Modify Bitwarden into BitBetter.

```bash
# Clone BitBetter repository
git clone git@github.com:jakeswenson/BitBetter.git bitbetter
cd bitbetter

# Build and install BitBetter
sudo ./build.sh
```

**Comment by JeffAlyanak** [comment]
You probably want to give docker permission to user other than root:

```bash
sudo usermod -aG docker some_user
```
At which point you can run the build script without sudo.

But yeah, it looks like you're on the right track. Once those steps are complete you should be able to go through the rest of the instructions in the readme to generate a license.

**Comment by tukusejssirs** [comment]
> While I'm happy to look into putting specific version number requirements into the dependency section, I don't think it's a good idea to include package names. It would become very cluttered and I don't think I've ever seen documentation for cross-platform software include package names.

I was not talking about dependency versions (although it might be good to know the minimal working versions). As for package names: you already include one (`openssl`). As for `[i]t would become very cluttered`: that’s why I suggest to separate the docs (or guides/instructions) from `README.md`. As for `I've [n]ever seen documentation for cross-platform software include package names`: [Bitwarden](https://help.bitwarden.com/article/install-on-premise/#install-bitwarden) does, [Docker](https://docs.docker.com/install/linux/docker-ce/centos/) does (for Docker, see the sidebar).

> I understand your point of view regarding docker, but I disagree that our docs should include guidance on installing or setting up docker. Again, there are just too many different configurations to cover and the docker docs are already quite complete and supplemented very well by countless community-created tutorials and youtube videos.

Maybe I did not use the proper wording (my thoughts might be wrongly ‘encoded’ into words) and you got ‘decoded’ them with different ‘decoder’. :smile: Once again: I _don’t suggest_ to include the instructions how to install Docker, but I suggest to include a note and link (hyperlink if you wish) to [this Docker installation guide](https://docs.docker.com/install/linux/docker-ce/centos/) (or better yet: to [CentOS](https://docs.docker.com/install/linux/docker-ce/centos/), [Debian](https://docs.docker.com/install/linux/docker-ce/debian/), [Fedora](https://docs.docker.com/install/linux/docker-ce/fedora/), [Ubuntu](https://docs.docker.com/install/linux/docker-ce/ubuntu/)). These instructions might change over time, therefore we should instruct our users to the mainstream source of information how to install the Docker.

> Regarding people reporting issues, if there are any issues in the install process I'd much prefer to solve that in the software itself rather than adding workarounds to the docs but if you can point out any issues that can't be solved easily I would add that to the docs until such a time that I could solve it properly.

Agreed, it is the proper way to deal with the issues. But currently:
1. there is no mention of _offline-running_ BW/BB in the `README.md` and other stuff I have learned from the _closed_ issues only;
2. if something is to be dealt with in the (near or far) future, I think it should be noted _now_ in the `README.md`/docs that this is the issue/problem/bug/enhancement that is to be worked on, currently there is this kind of workaround (like you did for the Company name in BB) and later on replace the text of _workaround_ with _solution_.

But this is lesser problem (to me) than the installation instructions.

I suggest to add some of this remarks to the `USAGE.md` (or similar) file where would be the usage instructions.

> On the issue of root, it simply sounds like you haven't given your user permission to use docker. Again, this is covered very fully in Docker's documentation and in tutorials. I'd highly recommend that you dive into that a bit before deploying software with Docker.

I see you talk about [this](https://docs.docker.com/install/linux/linux-postinstall/) guide (although it is not absolutely secure thing according to [this](https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface), source from [here](https://askubuntu.com/a/1165880/279745)). Another note should be add to the installation guide IMO.

> While it is already stated in the first line of the doc, I can certainly improve the description of the software to make it more clear that as a modification of Bitwarden, you'll need to first have a working installation of Bitwarden set up. That's a good suggestion.

:+1: I should have put it that simply in the first place. :smile:

---

All in all: I think we have (quite) same opinion what should be in the `README.md`/docs, but the language barrier is sort of blocking us to understand each other. :smile:

**Comment by tukusejssirs** [comment]
I have some more questions:

1. When attempting to replace `bitwarden/identity` with `bitbetter/identity`, I have found that in `bwdata/docker/docker-compose.yml` there is `/etc/bitwarden/identity` (see the `grep` output below). Should I replace `/etc/bitwarden/identity` with `/etc/bitbetter/identity` too? I presume that this path should be kept as it is, but I want to be sure.

```bash
$ grep bitwarden/identity bwdata/docker/docker-compose.yml
    image: bitwarden/identity:1.32.0
      - ../identity:/etc/bitwarden/identity
```

If it is so (i.e. the path / folder name should not be changed), I suggest to add the following two commands to the installation guide:

```bash
sed -i 's#bitwarden/api#bitbetter/api.*#;s#image: bitwarden/identity.*#image: bitbetter/identity#' [path_to_bw_bwdata]/docker/docker-compose.yml
sed -E ':a;N;$!ba;s/\r{0,1}\n/\\n/g' [path_to_bw_bwdata]/scripts/run.sh | sed "s/\(function restart() {[^}]*\)\(dockerComposePull\)\([^}]*}\)/\1# \2\3/" | sed 's/\\n/\n/g' > [path_to_bw_bwdata]/scripts/run.sh.tmp && /bin/rm [path_to_bw_bwdata]/scripts/run.sh && mv [path_to_bw_bwdata]/scripts/run.sh{.tmp,}
```

2. I think these changes should be done _before_ running `./bitwarden.sh install` and `./bitwarden.sh start`. I want you to confirm this. Thanks.

**Comment by JeffAlyanak** [comment]
@tukusejssirs Thanks for the questions.

>     1. I think these changes should be done _before_ running `./bitwarden.sh install` and `./bitwarden.sh start`. I want you to confirm this. Thanks.

Before embarking on any of the steps to patch it with BitBetter, bitwarden should already be installed! You probably also want to run it and create at least one user, so you'll already have run  `./bitwarden.sh install` and `./bitwarden.sh start` _before_ you start anything to do with BitBetter.

>     1. When attempting to replace `bitwarden/identity` with `bitbetter/identity`, I have found that in `bwdata/docker/docker-compose.yml` there is `/etc/bitwarden/identity` (see the `grep` output below). Should I replace `/etc/bitwarden/identity` with `/etc/bitbetter/identity` too? I presume that this path should be kept as it is, but I want to be sure.

As per a discussion you can find [here](https://github.com/jakeswenson/BitBetter/issues/45#issuecomment-562567580), we will be updating this part of the process soon. In the meantime, my recommendation is to leave the `docker-compose.yml` alone and simply create a new file in that directory called `docker-compose.override.yml` with the following content:

```bash
version: '3'

services:
   api:
    image: bitbetter/api
  identity:
    image: bitbetter/identity
```

This with automatically override only the values we wish to override — the image names called by the api and identity services.

**Comment by JeffAlyanak** [comment]
Since this is already in the docs and the issue #45 covers the automation of the process, I'm closing this ticket now.
