### ISSUE TITLE
Build Script should Generate docker-compose.override.yml

### ISSUE THREAD

**Issue by tam481** [jakeswenson/BitBetter#45]
Hello,
Are there any specific instructions for updating Bitwarden while using BitBetter? 

running ./bitwarden.sh update will not update the images as the config.yml file is modified to not regenerate the docker-compose.yml as part of the BitBetter installation.

Also, is it possible to modify the docker paramters by using docker-compose.override.yml instead of modifying the main docker-compose.yml file? so that the api and identity images use BitBetter instead of Bitwarden's?

Thanks in advance

**Comment by JeffAlyanak** [comment]
An upcoming update to BitBetter will include an upgrade script. I've added a note to also look at using a docker-compose override to make that modification cleaner, too. Thanks for that suggestion. 

If you run the bitwarden.sh's update-self option and then run the bitwarden update you'll be able to upgrade bitwarden pretty painlessly since the update-self process overwrites the bitwarden.sh script itself.

Then you'll need to follow the bitbetter instructions again, though don't need to regenerate any licenses. Since BitBetter will not overwrite the signing keys generated the first time you used it your existing licenses will still work.

That all said, be very careful around updates as future versions of bitwarden have no guarantee of working with bitbetter. Unless you see us update the Readme to indicate that we've tested bitbetter with a new update, be extra careful.

**Comment by tam481** [comment]
Thank you very much @JeffAlyanak 
I've done the following and upgraded successfully

Stopped Bitwarden - 
./bitwarden.sh stop

Created copies of the following:
bitwarden.sh
bwdata/

Self-updated
./bitwarden.sh updateself

Created a docker-override yml file for the API and Identity services to reference BitBetter

Modified the config.yml file to allow the docker-compose.yml file to be regenerated

Updated
./bitwarden.sh update

That failed (expected) as it tried to pull the images for BitBetter
 Manually modified the bwdata/scripts/run.sh to comment out "#    dockerComposePull"

Started Bitwarden to download the remaining images and start the program
./bitwarden.sh start

I hope people find this useful

**Comment by sutidor** [comment]
hey tam481, can you please elaborate on 
`Created a docker-override yml file for the API and Identity services to reference BitBetter
Modified the config.yml file to allow the docker-compose.yml file to be regenerated`

When updating I get:
untagged: bitbetter/identity:latest
deleted: sha256:...
untagged: bitwarden/identity:1.32.0
untagged: bitbetter/licensegen:latest
deleted: sha256:...
untagged: bitbetter/api:latest

And needless to say, bitbetter stopped working.

**Comment by tam481** [comment]
Hi @sutidor 
Sorry to hear you had problems. 

Inside "_/bwdata/docker/_" I used nano to create a new yml file called 
_docker-compose.override.yml_

The contents are as follows:

```
#
# Useful references:
# https://docs.docker.com/compose/compose-file/
# https://docs.docker.com/compose/reference/overview/#use--f-to-specify-name-and-path-of-one-or-more-compose-files
# https://docs.docker.com/compose/reference/envvars/
#
#########################################################################
# WARNING: This file is generated. Do not make changes to this file.    #
# They will be overwritten on update. If you want to make additions to  #
# this file, you can create a `docker-compose.override.yml` file in the #
# same directory and it will be merged into this file at runtime. You   #
# can also manage various settings used in this file from the           #
# ./bwdata/config.yml file for your installation.                       #
#########################################################################

version: '2'

services:
  api:
    image: bitbetter/api:latest
    container_name: bitwarden-api
    restart: always
    volumes:
      - ../core:/etc/bitwarden/core
      - ../ca-certificates:/etc/bitwarden/ca-certificates
      - ../logs/api:/etc/bitwarden/logs
    env_file:
      - global.env
      - ../env/uid.env
      - ../env/global.override.env

  identity:
    image: bitbetter/identity:latest
    container_name: bitwarden-identity
    restart: always
    volumes:
      - ../identity:/etc/bitwarden/identity
      - ../core:/etc/bitwarden/core
      - ../ca-certificates:/etc/bitwarden/ca-certificates
      - ../logs/identity:/etc/bitwarden/logs
    env_file:
      - global.env
      - ../env/uid.env
      - ../env/global.override.env
```
I used nano to also edit the config.yml file inside "/bwdata/" and changed the following line:

`generate_compose_config: true`

**Comment by sutidor** [comment]
1 little tweak:

`version: '2'`
had to be version: '3'

Runs like a dog after the ball. Thanks!

**Comment by JeffAlyanak** [comment]
@sutidor @tam481 

Your override config only needs to override the image. So you can simply use:

```docker-compose
version: '3'

services:
   api:
    image: bitbetter/api
  identity:
    image: bitbetter/identity
```

I'm going to add this to the BitBetter scripts so that this step is automatically dealt with in future versions and no more manual editing of of the `docker-compose.yml` is required.

**Comment by JeffAlyanak** [comment]
Closing several related issues which have been soved in PR https://github.com/jakeswenson/BitBetter/pull/69.

Only issue https://github.com/jakeswenson/BitBetter/issues/67 will remain open until the merge to master.
