### ISSUE TITLE
What is 'username' for generating a user license?

### ISSUE THREAD

**Issue by ndemarco** [jakeswenson/BitBetter#47]
Running the licenseGen script interactively requests the 'username' as part of the process:  'Please provide the username this license will be registered to. [username]:' It is unclear what I should enter for a license key username.

BitWarden seems to use the email address as the user ID. The Admin panel (/admin/users/view/guid-of-user) doesn't display a username.

What should I enter for username?

**Comment by JeffAlyanak** [comment]
@ndemarco  I'm not sure if this is a legacy element of the license or what its exact history is but the current versions of Bitwarden seem to ignore this value. You can just put the user's email address, their name or their favourite colour. Previous versions of Bitwarden did not like this field to be blank, but I'm not sure if that's still true.

Future versions of BitBetter might simply put the email address in there automatically but I haven't yet tested for any issues that might cause.
