### ISSUE TITLE
[Question] BitBetter vs Removing Licencing

### ISSUE THREAD

**Issue by Ornias1993** [jakeswenson/BitBetter#48]
It seems to be relatively easy to override Bitwarden Licencing when building from scratch and scratch builds aren't that hard either (and due to AGPL it's fine to even host self-build docker images).
See:
https://github.com/imi415/bitwarden-server/tree/communism

With a little bit of magic it could be pretty much automated (install, update etc) the same way as bitwarden does.

Isn't this a much cleaner solution than overwriting a pre-build binary?

Edit
Even if the goal is to make licencing available to self-hosted users, isn't the right way of doing so just forking the codebase?

**Comment by JeffAlyanak** [comment]
@Ornias1993 Frankly, had I undertaken this project myself from scratch that would likely have been the approach I would have taken. I have previous done exactly that with the Openbravo codebase and it has the potential to be the cleanest solution.

The downside to a hard fork, however, is the need to consistently keep the codebase up-to-date with the latest changes made upstream. Given the way that the bitwarden repositories are organized, it would require either the forking of multiple repositories or some significant reorganization of the forked repos. Either way, that's a lot to stay on top of when keeping the fork up-to-date with upstream fixes, new versions etc.

Although it's very underdeveloped currently and works perfectly fine, our solution is not as simple as a fork for the end user. However, it requires a very minimal amount of development work compared to a total codebase fork and I believe that with a small amount of work it can eventually become a "two click solution" — users install Bitwarden with one command and then patch it with BitBetter with another single command.

**Comment by JeffAlyanak** [comment]
Note: I'm closing this issue, but not locking discussion. I think it's interesting to discuss alternative solutions here, but I think actually implementing them is beyond the scope of this project.

**Comment by Ornias1993** [comment]
@JeffAlyanak I understand closing is the cleanest solution.

I agree that too many changes tend to spiral out of control maintenance wise, for example there is a guy who did this and actually removed any and all references to licencing (20.000+ rows of code). And yes, this creates a unmaintainable mess of merge conflicts.

I myself managed to get a much cleaner solution than the earlier mentioned issue working here:
https://github.com/Open-Bitwarden/server

Most changes are due to forcing it to use a different dockerhub location. The only actual code changes to always accept any licence (aka override the checks) are just 3 rows.

With AppVeyor it's quite maintainable, Merge new changes in, re-run appveyor and everything solves itself. It shouldn't give too many merge conflicts.

Due to the design of this piece of software, it should be relatively maintainable to add the licence generator included in its own file, which would limit the amount of code changes in the actual codebase.

**Comment by JeffAlyanak** [comment]
> I myself managed to get a much cleaner solution than the earlier mentioned issue working here:
> https://github.com/Open-Bitwarden/server
> 
> Most changes are due to forcing it to use a different dockerhub location. The only actual code changes to always accept any licence (aka override the checks) are just 3 rows.
> 
> With AppVeyor it's quite maintainable, Merge new changes in, re-run appveyor and everything solves itself. It shouldn't give too many merge conflicts.
> 

I'll definitely be checking that out, if you ever need some help maintaining it going forward please feel free to reach out.

One concern you might have is using the Bitwarden name and logo. I haven't looked into it, but those are often not covered under their source-code licensing terms. That said, if you needed help "rebranding" it, I'd also be happy to help with that.

**Comment by Ornias1993** [comment]
@JeffAlyanak
Thanks for the offer!

I think including a cert-authority might (in the future) prove to be a cleaner solution than a licence file hack. My current school of thought:
1. Move licence file out of DLL
2. Create /bwdata/licensing and link to the required docker containers
3. If there is a different cert under /bwdata/licensing, copy it on docker run.
4. remove/disable fingerprinting of the cert (because it's totally useless on opensource host-only licensing certs)

Future:
Include generating the cert(s)
All 4 should be doable with minimal code changes.

trademark wise (while the (non "open-")bitwarden references it should be changed in the future for sure. However, (luckily) use of the logo and name is covered under the Github TOS for forking.

**Comment by Ornias1993** [comment]
Okey, I at least got:
- the license file moved out of the DLL, 
- it now replaces it with the one under /bwdata/licensing if present
- Thumbprint gets calculated based on said file.

Seems to be working rather smoothly.

I'm now working on including the LicenseGenerator in the project.

**Comment by Ornias1993** [comment]
I quickly hacked it together today, there ya go:
https://github.com/Open-Bitwarden/server/pull/1
