### ISSUE TITLE
dotnet add package Newtonsoft.Json -

### ISSUE THREAD

**Issue by firelook** [jakeswenson/BitBetter#5]
I have tryed but 

root@security:~/dotnet# dotnet add package Newtonsoft.Json --version 11.0.0
Could not find any project in `/root/dotnet/`.
Usage: dotnet add <PROJECT> package [options] <PACKAGE_NAME>

**Comment by JeffAlyanak** [comment]
@firelook Why are you doing that as root? I simply installed that package as a regular user in the docker host and then rebuilt the licensegen.

**Comment by firelook** [comment]
no clues how to do that.
would you mind to do a help on this please ? (step by step for dummies ...)

**Comment by JeffAlyanak** [comment]
So, on the host machine - the machine on which docker is installed, but not inside any of the docker containers - have you been following the entire install process as the root user?

You generally never want to use the root account for anything that doesn't require root privileges, so if that's how you've been doing the install I'd start from scratch and do it as a regular user instead.

The process I followed to get this entire thing working is as follows. First, prepare everything you need to get started:

- As a regular user (in my case I created a user called bw), install bitwarden and all it's dependencies by following the standard instructions as listed on the bitwarden website
- As a regular user use `wget` or `git` to clone this BitBetter repository
- Install the .NET core and .NET dev packages
- Use the newly installed .NET core to run the command `dotnet add package Newtonsoft.Json --version 11.0.0`

Now you've got everything you need to start. There are a few things you can do out of order here, but here's one way:

- Generate the public/private key and convert to PFX using the instructions in the BitBetter README.md and place all that in the BitBetter/.keys directory
- run `./BitBetter/build.sh`

Now, inside your bitwarden directory edit the `bwdata/docker/docker-compose.yml` to change the image loaded for the api:

Change:
```
...
  api:
    image: bitwarden/api:x.x.x
    container_name: bitwarden-api
    restart: always
...
```
To:
```
...
  api:
    image: bitbetter/api:latest
    container_name: bitwarden-api
    restart: always
...
```

Still inside your bitwarden directory edit the `bwdata/scripts/run.sh` file. 

Change:
```
function restart() {
    dockerComposeDown
    dockerComposePull
    updateLetsEncrypt
    dockerComposeUp
    dockerPrune
    printEnvironment
}
```
To:
```
function restart() {
    dockerComposeDown
    #dockerComposePull
    updateLetsEncrypt
    dockerComposeUp
    dockerPrune
    printEnvironment
}
```
You can now start/restart bitwarden and it will use the new bitbetter-api.

Now you need to generate user and/or org licenses. First, build the licenseGen tool:
```
./BitBetter/src/licenseGen/build.sh
```

Next, run it with:
```
./src/licenseGen/run.sh /root/github/BitBetter/cert.pfx org name email id
```

It'll spit out a json-formatted license.

**Comment by firelook** [comment]
no differences

`
Oops: System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.

File name: 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.IsCustomAttributeDefined(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Int32 attributeCtorToken, Boolean mustBeInheritable)
   at System.Attribute.InternalIsDefined(PropertyInfo element, Type attributeType, Boolean inherit)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.GetSerializableMembers(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperties(Type type, MemberSerialization memberSerialization)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at bitwardenSelfLicensor.Program.GenerateOrgLicense(X509Certificate2 cert, String corePath, String userName, String email, Guid instalId, String key) in /root/github/BitBetter/src/licenseGen/Program.cs:line 217
   at bitwardenSelfLicensor.Program.<>c__DisplayClass0_2.<Main>b__6() in /root/github/BitBetter/src/licenseGen/Program.cs:line 121
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at bitwardenSelfLicensor.Program.Main(String[] args) in /root/github/BitBetter/src/licenseGen/Program.cs:line 137
`

**Comment by firelook** [comment]
> dotnet add package Newtonsoft.Json --version 11.0.1
  Writing /tmp/tmpcios0Q.tmp
info : Adding PackageReference for package 'Newtonsoft.Json' into project '/root/dotnet/dotnet.csproj'.
log  : Restoring packages for /root/dotnet/dotnet.csproj...
info :   CACHE https://api.nuget.org/v3-flatcontainer/newtonsoft.json/index.json
warn : dotnet depends on Newtonsoft.Json (>= 11.0.0) but Newtonsoft.Json 11.0.0 was not found. An approximate best match of Newtonsoft.Json 11.0.1 was resolved.
info : Package 'Newtonsoft.Json' is compatible with all the specified frameworks in project '/root/dotnet/dotnet.csproj'.
^[Oinfo : PackageReference for package 'Newtonsoft.Json' version '11.0.1' updated in file '/root/dotnet/dotnet.csproj'.

**Comment by firelook** [comment]
any users (or root) will have the same logic: my dotnet is under root (you can acess to create everything) except this newtonsoft (where something weirds with this package)

**Comment by JeffAlyanak** [comment]
Usually the environment variables for the root user are different and many programs will not run properly under root.

As far as I'm aware, dotnet is not intended to be run under root like that. If you insist on using root then you might have to dig deeper into the environment variables that dotnet uses.

**Comment by firelook** [comment]
I have done the same steps with an other user, takes time but same problems
I suspect something is wrong in your program.cs : 
`
using Newtonsoft.Json;
`

=> if I put in comment this line no difference

P.S.
if I gave you my cert and my "org" on email ( ? ) can you generate it for me ?
worst case scenario

**Comment by JeffAlyanak** [comment]
Well, I didn't write the program but the `using Newtonsoft.Json;` is correcy syntax and worked perfectly fine for me.

**Comment by JeffAlyanak** [comment]
Did you run the command `dotnet add package Newtonsoft.Json --version 11.0.0` in the  `BitBetter/src/licenseGen/` directory or elsewhere? Did it complete with a success message or something else?

**Comment by firelook** [comment]
in the directory where I installed dotnet the package is ok

in the BitBetter/src/licenseGen => no (and if I run it at this level it sayed the package can not be found)

**Comment by firelook** [comment]
it is looking for ` 'Newtonsoft.Json, Version=11.0.0.0, `
but I have `11.0.1`

**Comment by firelook** [comment]
any suggestions

**Comment by firelook** [comment]
what else can you propose ?

**Comment by JeffAlyanak** [comment]
Well, after running your last command in the ./BitBetter/src/licenseGen/ directory you got the output:

```
~/github/BitBetter/src/licenseGen# dotnet add package Newtonsoft.Json --version 11.0.0 Writing /tmp/tmpczV0bh.tmp info : Adding PackageReference for package 'Newtonsoft.Json' into project '/root/github/BitBetter/src/licenseGen/licenseGen.csproj'. log : Restoring packages for /root/github/BitBetter/src/licenseGen/licenseGen.csproj... info : CACHE https://api.nuget.org/v3-flatcontainer/newtonsoft.json/index.json warn : licenseGen depends on Newtonsoft.Json (>= 11.0.0) but Newtonsoft.Json 11.0.0 was not found. An approximate best match of Newtonsoft.Json 11.0.1 was resolved. info : Package 'Newtonsoft.Json' is compatible with all the specified frameworks in project '/root/github/BitBetter/src/licenseGen/licenseGen.csproj'. info : PackageReference for package 'Newtonsoft.Json' version '11.0.0' updated in file '/root/github/BitBetter/src/licenseGen/licenseGen.csproj'.
```\
So, now you can run ./BitBetter/src/licenseGen/build.sh and you should see some output saying something like this:
```
./BitBetter/src/licenseGen/licenseGen.csproj : warning NU1603: licenseGen depends on Newtonsoft.Json (>= 11.0.0) but Newtonsoft.Json 11.0.0 was not found. An approximate best match of Newtonsoft.Json 11.0.1 was resolved.
  Restore completed in 81.79 ms for ./BitBetter/src/licenseGen/licenseGen.csproj.
Microsoft (R) Build Engine version 15.7.177.53362 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

./BitBetter/src/licenseGen/licenseGen.csproj : warning NU1603: licenseGen depends on Newtonsoft.Json (>= 11.0.0) but Newtonsoft.Json 11.0.0 was not found. An approximate best match of Newtonsoft.Json 11.0.1 was resolved.
  Restore completed in 45.72 ms for ./BitBetter/src/licenseGen/licenseGen.csproj.
./BitBetter/src/licenseGen/licenseGen.csproj : warning NU1603: licenseGen depends on Newtonsoft.Json (>= 11.0.0) but Newtonsoft.Json 11.0.0 was not found. An approximate best match of Newtonsoft.Json 11.0.1 was resolved.
  licenseGen -> ./BitBetter/src/licenseGen/bin/Debug/netcoreapp2.0/licenseGen.dll
  licenseGen -> ./BitBetter/src/licenseGen/bin/Debug/netcoreapp2.0/publish/
Sending build context to Docker daemon  1.313MB
Step 1/3 : FROM bitbetter/api
 ---> c1615029b1e8
Step 2/3 : COPY bin/Debug/netcoreapp2.0/publish/* /app/
 ---> Using cache
 ---> 0c559ee30e1e
Step 3/3 : ENTRYPOINT [ "dotnet", "/app/licenseGen.dll", "--core", "/app/Core.dll", "--cert", "/cert.pfx" ]
 ---> Using cache
 ---> 08af94a73434
Successfully built 08af94a73434
Successfully tagged bitbetter/licensegen:latest
```

If not, what do you see when you run the build after having successfully installed the Newtonsoft.Json 11.0.1 package?

**Comment by firelook** [comment]
the build is working perfectly !

**Comment by JeffAlyanak** [comment]
Then what is the issue?

**Comment by firelook** [comment]
do you need more information ?

**Comment by firelook** [comment]
no more suggestion you want me to test ?

**Comment by JeffAlyanak** [comment]
What output do you get upon running the licensegen/build.sh?
What output do you get upon running the licensegen/run.sh?

**Comment by firelook** [comment]
build : 
`
 ./build.sh
mkdir: cannot create directory ‘./src/bitBetter/.keys’: File exists
  Restore completed in 596.28 ms for /root/github/BitBetter/src/bitBetter/bitBetter.csproj.
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  bitBetter -> /root/github/BitBetter/src/bitBetter/bin/Debug/netcoreapp2.0/bitBetter.dll
  bitBetter -> /root/github/BitBetter/src/bitBetter/bin/Debug/netcoreapp2.0/publish/
Sending build context to Docker daemon  697.3kB
Step 1/4 : FROM bitwarden/api
latest: Pulling from bitwarden/api
be8881be8156: Pull complete
f854db899319: Pull complete
4591fd524b8e: Pull complete
65f224da8749: Pull complete
8812bf9c4e41: Pull complete
992cf74495ea: Pull complete
064959fe0292: Pull complete
063b9f99686f: Pull complete
1edfb399f997: Pull complete
5bb5ee030b9a: Pull complete
362f24613823: Pull complete
Digest: sha256:fc5c3e3adba0c11bf6d7152f396509e5bd5da80880ba3acb4eecc419b1106df9
Status: Downloaded newer image for bitwarden/api:latest
 ---> 1a38b2747165
Step 2/4 : COPY bin/Debug/netcoreapp2.0/publish/* /bitBetter/
 ---> f17a92d5c76e
Step 3/4 : COPY ./.keys/cert.cert /newLicensing.cer
 ---> b916e20da8a5
Step 4/4 : RUN dotnet /bitBetter/bitBetter.dll &&     echo "modified dll" &&     mv /app/Core.dll /app/Core.orig.dll &&     mv /app/modified.dll /app/Core.dll &&     cp -f /app/Core.dll /jobs/Core.dll &&     echo "replaced dll" &&     rm -rf /bitBetter && rm -rf /newLicensing.cer &&     echo "cleaned up"
 ---> Running in 2d3a02a4a88e
Bit.Core.licensing.cer
Existing Cert Thumbprin: B34876439FCDA2846505B2EFBBA6C4A951313EBE
New cert Thumbprint: 0B7800A32E6DAD5719139ACB988CCF0AB132FE39
modified dll
replaced dll
cleaned up
Removing intermediate container 2d3a02a4a88e
 ---> 937cf0b06f72
Successfully built 937cf0b06f72
Successfully tagged bitbetter/api:latest

`

**Comment by firelook** [comment]
run
`
Oops: System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.

File name: 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.IsCustomAttributeDefined(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Int32 attributeCtorToken, Boolean mustBeInheritable)
   at System.Attribute.InternalIsDefined(PropertyInfo element, Type attributeType, Boolean inherit)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.GetSerializableMembers(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperties(Type type, MemberSerialization memberSerialization)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at bitwardenSelfLicensor.Program.GenerateOrgLicense(X509Certificate2 cert, String corePath, String userName, String email, Guid instalId, String key) in /root/github/BitBetter/src/licenseGen/Program.cs:line 217
   at bitwardenSelfLicensor.Program.<>c__DisplayClass0_2.<Main>b__6() in /root/github/BitBetter/src/licenseGen/Program.cs:line 121
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at bitwardenSelfLicensor.Program.Main(String[] args) in /root/github/BitBetter/src/licenseGen/Program.cs:line 137
`

**Comment by JeffAlyanak** [comment]
Are you still running this as root? Like I said before, the environment variables on dotnet do not work well with the root account. If you haven't been running it as root, then I've really run out of suggestions.

**Comment by firelook** [comment]
have you tested on ubuntu server18.04 ?

**Comment by JeffAlyanak** [comment]
Going from a fresh install of Ubuntu 18.04.1 LTS Server and following the instructions I put together earlier succeeds for me.

**Comment by firelook** [comment]
where did you download dotnet and how you install it please ?

**Comment by firelook** [comment]
ok with latest dotnet ir worked !!!!!

last 2 questions : 
1/ it is for one year => how to make 30 years (for example) ?
2/ org => family , jow to make premium ?

thanks !

**Comment by JeffAlyanak** [comment]
@firelook 

I'm guessing you're not a programmer?

Look at the file `src/licenseGen/Program.cs` at line 160 and 192.

User License:
```
            set("LicenseKey", string.IsNullOrWhiteSpace(key) ? Guid.NewGuid().ToString("n") : key);
            set("Id", userId);
            set("Name", userName);
            set("Email", email);
            set("MaxStorageGb", short.MaxValue);
            set("Premium", true);
            set("Version", 1);
            set("Issued", DateTime.UtcNow);
            set("Refresh", DateTime.UtcNow.AddYears(1).AddMonths(-1));
            set("Expires", DateTime.UtcNow.AddYears(1));
            set("Trial", false);
```

Org License:
```
             set("LicenseKey", string.IsNullOrWhiteSpace(key) ? Guid.NewGuid().ToString("n") : key);
            set("InstallationId", instalId);
            set("Id", Guid.NewGuid());
            set("Name", userName);
            set("BillingEmail", email);
            set("BusinessName", "BitBetter");
            set("Enabled", true);
            set("Seats", (short)5);
            set("MaxCollections", short.MaxValue);
            set("MaxStorageGb", short.MaxValue);
            set("SelfHost", true);
            set("UseGroups", true);
            set("UseDirectory", true);
            set("UseTotp", true);
            set("PlanType", (byte)6);
            set("Plan", "Custom");
            set("Version", 1);
            set("Issued", DateTime.UtcNow);
            set("Refresh", DateTime.UtcNow.AddYears(1).AddMonths(-1));
            set("Expires", DateTime.UtcNow.AddYears(1));
            set("Trial", false);
```

Things you might want to change:

* Change all of the `AddYears(1)` to `AddYears(100)`
* Change `set("Seats", (short)5);` to `set("Seats", (short)32,767);`

**Comment by firelook** [comment]
are you sure it is the right program ? => doesn't change anything

**Comment by firelook** [comment]
no errors , just doesn't take your variable

**Comment by JeffAlyanak** [comment]
@firelook Line 165 should already show `set("Premium", true);`

If it doesn't, make sure it does.

**Comment by JeffAlyanak** [comment]
Each user needs only one json license.

**Comment by leejosh** [comment]
I have tried your instructions and i get this error;

cp: cannot create regular file '/jobs/Core.dll': No such file or directory
The command '/bin/sh -c dotnet /bitBetter/bitBetter.dll &&     echo "modified dll" &&     mv /app/Core.dll /app/Core.orig.dll &&     mv /app/modified.dll /app/Core.dll &&     cp -f /app/Core.dll /jobs/Core.dll &&     echo "replaced dll" &&     rm -rf /bitBetter && rm -rf /newLicensing.cer &&     echo "cleaned up"' returned a non-zero code: 1

**Comment by JeffAlyanak** [comment]
@leejosh Which steps have you followed? Which command returns this error?

**Comment by jakeswenson** [comment]
@leejosh please see #8 @JeffAlyanak mind getting a PR in for the newton soft fix? i'll close this issue once its resolved.

Thanks for all the debuging/help @JeffAlyanak

**Comment by firelook** [comment]
I have updated to latest update : and now my organisation is de activated, tryed to regenerate nothing is working any more, any suggestions please ?

**Comment by JeffAlyanak** [comment]
> 
> 
> @leejosh please see #8 @JeffAlyanak mind getting a PR in for the newton soft fix? i'll close this issue once its resolved.
> 
> Thanks for all the debuging/help @JeffAlyanak

I don't think there's actually any issue to be fixed here. It works fine without making any changes, I mostly just talked @firelook through following the correct steps to build it.

**Comment by JeffAlyanak** [comment]
This seems to have been solved for a while. Some documentation might need to be written to be more clear, but it _is_ all there and it works.
