### ISSUE TITLE
Organization Does Not Show

### ISSUE THREAD

**Issue by robocoder99** [jakeswenson/BitBetter#51]
When I add an organization via my user account using the license generated by BitBetter the operation completes successfully but the organization does not appear linked to my user account. However, the organization does show up in the admin panel. Does anyone have any experience with this? I can offer any logs files necessary.

**Comment by JeffAlyanak** [comment]
@robocoder99 

After adding the organization to your account you still see this?

> You do not belong to any organizations. Organizations allow you to securely share items with other users.

What version of Bitwarden are you using?

**Comment by robocoder99** [comment]
Yes, 1.32.0

**Comment by JeffAlyanak** [comment]
Hey @robocoder99, I'm having trouble replicating this issue. Can you provide any more details about the process you're following?

**Comment by captainhook** [comment]
@robocoder99 are you still seeing this problem? Did you remove yourself from the org at any point?

**Comment by captainhook** [comment]
This is a very old issue and we cannot replicate nor is @robocoder99 responding here so I'll close this.
