### ISSUE TITLE
The framework 'Microsoft.NETCore.App', version '2.0.0' was not found.

### ISSUE THREAD

**Issue by phamthanhnhan14** [jakeswenson/BitBetter#55]
Hi,
./build.sh failed in step 5.
Step 5/5 : RUN set -e; set -x;     dotnet /bitBetter/bitBetter.dll &&     mv /app/Core.dll /app/Core.orig.dll &&     mv /app/modified.dll /app/Core.dll &&     rm -rf /bitBetter && rm -rf /newLicensing.cer
 ---> Running in bebebdbeef85
+ dotnet /bitBetter/bitBetter.dll
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.0.0' was not found.
  - The following frameworks were found:
      3.1.2 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.0.0&arch=x64&rid=debian.10-x64
Could you please check?

**Comment by JeffAlyanak** [comment]
Hi @phamthanhnhan14, can you confirm that you're on the latest commit? We just pushed a patch that updates the version of .net core.

**Comment by JeffAlyanak** [comment]
@phamthanhnhan14 I'm closing this issue because, given no further details, I have to assume this is referring to the issues fixed in pull request https://github.com/jakeswenson/BitBetter/pull/54.
