### ISSUE TITLE
After adding Org license, and inviting users, the users are not in that organization.

### ISSUE THREAD

**Issue by mcdade** [jakeswenson/BitBetter#57]
So here's what I have, able to generate the Org license, imports fine and seems to unlock the features.  I then go to the panel and invite a user.  The user gets the email, signs up and logs in to the account, however they are not part of the org and the user was as if they just created a standalone account in the system.  I can create a new org license for the user, however then they are put into their own org.  It's like they just aren't connected.

**Comment by captainhook** [comment]
Hi @mcdade 
Did you resolve this? After they sign up and verify their account you do need to approve them from the org membership list.
