### ISSUE TITLE
Can't install on debian

### ISSUE THREAD

**Issue by mariopampa** [jakeswenson/BitBetter#6]
I can't install on debian 9. 
Could you provide me a step by step to install? 
Thanks,

Mario

**Comment by online-stuff** [comment]
I got most of it installed starting from a minimal install of Stretch

Generating licenses, but they are 'invalid' when trying to add them to my account..  So close, but not there yet

**Comment by jakeswenson** [comment]
This is a docker container... you shouldn't need to install anything?
@online-stuff did you get it resolved?

**Comment by online-stuff** [comment]
Starting from a clean/minimal Debian 9, you have to install/setup the install to run a Docker image for example.

**Comment by jakeswenson** [comment]
cool! closing

**Comment by tukusejssirs** [comment]
@online-stuff & @jakeswenson: I am all new to the `docker` stuff. The [`README.md`](https://github.com/jakeswenson/BitBetter#pre-requisites) says (as I interprete it) that there are only **two** dependencies:
- `docker`,
- `openssl`.

So I have installed them on CentOS 7 using `sudo yum -y install docker openssl`. Done successfully.

Then I have cloned the repo and entered the folder. Done successfully.

Then the `README.md` says that the last step is `./build.sh`, but it requires to be run as `root` (there should be a note about it in the `README.md`), so I did it—here is the output:

```bash
Generating a 4096 bit RSA private key
......................................................................................................++
..............................................................................................................................++
writing new private key to '/home/ts/a/home/ts/bb_2/.keys/key.pem'
-----
build.sh  README.md  src
sh: 0: Can't open build.sh
Sending build context to Docker daemon 10.75 kB
Step 1/5 : ARG BITWARDEN_TAG
Please provide a source image with `from` prior to commit
Sending build context to Docker daemon 10.75 kB
Step 1/5 : ARG BITWARDEN_TAG
Please provide a source image with `from` prior to commit
```

So it cannot open `build.sh`. I don’t know why. Should I install Bitwarden docker container? If yes, how? Should I install the upstream Bitwarden (using [these instructions](https://github.com/bitwarden/server#linux--macos)) first?

**Comment by JeffAlyanak** [comment]
@tukusejssirs Do you already have Bitwarden up and running?

**Comment by tukusejssirs** [comment]
All I have done is listed in my previous comment. Except for [`Bitwarden CLI`](https://github.com/bitwarden/cli), which I think is unrelated.

Therefore, I think that I _don’t_ have Bitwarden server even installed as I thought that `[repo_root]/build.sh` will download and installed it for me. Anyway, I have never done it, so could you please tell me the instructions or at least provide me with a link to them?

Thank you in advance. :)

**Comment by JeffAlyanak** [comment]
@tukusejssirs No, BitBetter only modifies an existing Bitwarden installation to allow you to generate your own licenses.
