### ISSUE TITLE
error when trying to build bit better - net framework

### ISSUE THREAD

**Issue by robina80** [jakeswenson/BitBetter#61]
hi all,

so ive installed the net framework 3.1 using this how to guide

https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1804

but when i build bitbetter i get this error message

+ dotnet /bitBetter/bitBetter.dll
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/share/dotnet/
  - Installing .NET Core prerequisites might help resolve this problem:
      https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      2.2.6 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

but when i check my version i have 3.1

root@lon-c-bw:/bitwarden/bwdata/BitBetter# dotnet --version
3.1.201

am i missing something here?

thanks,
rob

**Comment by robina80** [comment]
as you can see i have the sdk and runtime, i just dont get why this is happening

root@lon-c-bw:/bitwarden/bwdata/BitBetter# dotnet --list-sdks
3.1.201 [/root/dotnet/sdk]
root@lon-c-bw:/bitwarden/bwdata/BitBetter# dotnet --list-runtimes
Microsoft.AspNetCore.App 3.1.3 [/root/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.3 [/root/dotnet/shared/Microsoft.NETCore.App]
root@lon-c-bw:/bitwarden/bwdata/BitBetter#

**Comment by JeffAlyanak** [comment]
Hi @robina80 The dotnet build happens inside a container. You don't need to install dotnet stuff on your host machine.

The error you seem to be having was in issue we have recently patched. Can you confirm that you're using the latest commit faf7833?

**Comment by robina80** [comment]
When you say commit, do you mean the latest version of bitbetter

**Comment by JeffAlyanak** [comment]
@robina80 If you're unsure about what a commit is, your safest bet is to just remove the copy of bitbetter you have and download the latest version:

https://github.com/jakeswenson/BitBetter/archive/master.zip

**Comment by robina80** [comment]
mmm... i deleted the dir BitBetter and when running the build again i get the same errors

**Comment by robina80** [comment]
no the master copy didnt work, when i build it, im getting the same error

**Comment by JeffAlyanak** [comment]
Try deleting the docker images/containers before you rebuild them.

**Comment by robina80** [comment]
yeah thats wht i did deleted the microsfot sdk 2.1 as when i did a docker images i saw 3.1 and 2.1, so i deleted 2.1

**Comment by JeffAlyanak** [comment]
Can you just confirm the output of each of these commands:

```
docker ps
docker image ls
docker container ls
```

**Comment by robina80** [comment]
What I did was install a brand new server Ubuntu 1804, once did that I installed sdk core  via this

https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1804

Mkdir /bitwarden/bwdata

Cd /bitwarden/bwdata

git clone https://github.com/jakeswenson/BitBetter.git

/bitwarden/bwdata/BitBetter/build.sh

and I got no errors 

Once I built it I then copied my old bitwarden files in my /bitwarden/bwdata folder

Then ran this to get it going

docker-compose -f ./docker/docker-compose.yml up -d

I obviously changed the path to my docker compose yml file

You obviously need to install docker and docker compose on the server

**Comment by JeffAlyanak** [comment]
@robina80 You don't need the SDK on your host machine at all. The license generator is built entirely inside a container.

It's hard to tell exactly what was going wrong, but my best guess is that you still had an outdated docker container or image that wasn't being rebuilt and when running the build process for the license generator the out-of-date image was being used.

**Comment by robina80** [comment]
thanks Jeff,

i then realised when i did a docker images bitbetter api license gen and identity was running so maybe if i removed them it would had worked
