### ISSUE TITLE
Access bitbetter/api

### ISSUE THREAD

**Issue by majestic1488** [jakeswenson/BitBetter#63]
Hello!
I installed bitbetter/api and bitbetter/identity.
Added organization, now I want to use api to do mass mailing. Tell me where to get client_id and client_secret.

**Comment by JeffAlyanak** [comment]
Hi @majestic1488,

This is a core functionality of Bitwarden and it's outside the scope of our project. You can see the details on getting your client_id and client_secret from Bitwarden's own documentation:

https://help.bitwarden.com/article/public-api/#authentication

**Comment by majestic1488** [comment]
Yes, that is right.

It’s just written there "You can obtain your client_id and client_secret from your organization through the web vault. Navigate to your organization’s administrative area, then Settings → My Organization → API Key."


After installing the organization, it lacks an API key.
I wanted to ask if it’s possible to add this functionality to you.
