### ISSUE TITLE
Error in version 1.34.0

### ISSUE THREAD

**Issue by jacrespo64** [jakeswenson/BitBetter#66]
Hello

We have been with version 1.33 for a while but due to an incident we have had to reinstall everything again and we have automatically installed version 1.34.0, and that's when we discovered that it does not work with this version (I enclose screenshots of the error that appears).

![image](https://user-images.githubusercontent.com/64958703/83138200-ba808e00-a0ea-11ea-8c7a-aff6f7402fca.png)

![image](https://user-images.githubusercontent.com/64958703/83138368-f9164880-a0ea-11ea-9261-a0a6d050c6cc.png)

I want to ask you if an update for this version is available soon.

Thanks for everything

**Comment by JeffAlyanak** [comment]
Closing several related issues which have been solved in PR https://github.com/jakeswenson/BitBetter/pull/69.

Only issue https://github.com/jakeswenson/BitBetter/issues/67 will remain open until the merge to master.
