### ISSUE TITLE
API upgraded in 1.34.0

### ISSUE THREAD

**Issue by GieltjE** [jakeswenson/BitBetter#67]
The following now happens on every record update/add/delete attempt

```2020-05-30 15:23:08.537 +00:00 [Information] Api started.
2020-05-30 15:23:46.498 +00:00 [Error] Procedure or function 'CipherDetails_Update' expects parameter '@DeletedDate', which was not supplied.
System.Data.SqlClient.SqlException (0x80131904): Procedure or function 'CipherDetails_Update' expects parameter '@DeletedDate', which was not supplied.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader()
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 678
   at Bit.Core.Repositories.SqlServer.CipherRepository.ReplaceAsync(CipherDetails obj)
   at Bit.Core.Services.CipherService.SaveDetailsAsync(CipherDetails cipher, Guid savingUserId, IEnumerable`1 collectionIds, Boolean skipPermissionCheck)
   at Bit.Api.Controllers.CiphersController.Put(String id, CipherRequestModel model) in /home/appveyor/projects/server/src/Api/Controllers/CiphersController.cs:line 173
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
ClientConnectionId:65574c4f-c685-47d6-bf3a-3d4df775525f
Error Number:201,State:4,Class:16
```

Running without the modified API for now, seems to work ok (old licenses get kicked after sometime though).
Can't seem to figure out why it keeps using some old API

**Comment by tam481** [comment]
Please help @jakeswenson I upgraded to 1.34 and now I'm stuck.

**Comment by GieltjE** [comment]
Went digging through the source code, the patch itself is actualy nice and clean, well done :)
Got a bit annoyed by docker leaving to much crap about, so I decided to reset everyting docker related and work my way up to the problematic code.
However for some reason everything now works again, which probably means that there probably is some old version of bitwarden/api still being used instead of updated.

**Comment by tam481** [comment]
Hi @GieltjE 
So is it just a case of running "git pull" in the current BitBetter directory and then running the ./build.sh script? I take it this will recreate the bitbetter/api and bitbetter/identity.
Would I have to regenerate any licences I previously generated?
I haven't updated BitBetter since May 2019 which is when I first started using it.

**Comment by GieltjE** [comment]
First of all, always keep a backup of the .keys directory, this ensures there is no need to recreate all licenses.
Second, the problem lies somwhere within the /var/lib/docker/, my best guess is that because the bitbetter docker containers don't contain an version identifier they remain in the original version.

For the below steps ensure you have a backup of the bwdata directory (stop bitwarden first!) and a backup of the .keys directory too!

 - Try stopping the bitwarden server and pruning all items (docker system prune -a --volumes).
RestartHere:
 - Clear the BitBetter directory
 - Pull BitBetter
 - Build BitBetter (should pull the required Bitwarden elements)
 - Start Bitwarden (should pull all other required elements)
Move the bwdata folder if it complains it already exists, move it back after

If that doesn't work, ensure you know what you are doing and follow these steps, they are wat worked for me:
 - Stop bitwarden, and all other containers
 - Stop docker
 - Clear the /var/lib/docker/ directory
 -  Goto RestartHere;

**Comment by JeffAlyanak** [comment]
Hi @GieltjE, I just want to confirm that you now have Bitwarden 1.34.0 working as expected with the current release of BitBetter?

If so, I'd be inclined to add your troubleshooting steps to the Readme to ensure others don't get stumped by this issue.

**Comment by GieltjE** [comment]
@JeffAlyanak Yes I have the 1.34.0 release working with an unmodified release of BitBetter.
But we really need to figure out what's actually going on, as it seems to keep running on an older version of the underlying Bitwarden/api.

**Comment by dns13** [comment]
Pull request #69 fixed it for me. Thanks to @h44z.

**Comment by GieltjE** [comment]
@h44z, awesome work (also on the update script), would have taken me a long time since I'm not acquanted with docker.

**Comment by GieltjE** [comment]
@jakeswenson Could you please review the pull request and accept it?

**Comment by GieltjE** [comment]
@h44z, the update script has a problem with patching the .sh files:

```
./bitwarden.sh start
 _     _ _                         _
| |__ (_) |___      ____ _ _ __ __| | ___ _ __
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2020, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

Docker version 19.03.8, build afacb8b7f0
docker-compose version 1.26.0, build unknown

Removing network docker_default
WARNING: Network docker_default not found.
Removing network docker_public
WARNING: Network docker_public not found.
Pulling icons         ... done
Pulling events        ... done
Pulling mssql         ... done
Pulling api           ... error
Pulling attachments   ... done
Pulling admin         ... done
Pulling notifications ... done
Pulling identity      ... error
Pulling web           ... done
Pulling nginx         ... done

ERROR: for identity  pull access denied for bitbetter/identity, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

ERROR: for api  pull access denied for bitbetter/api, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
ERROR: pull access denied for bitbetter/api, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by robina80** [comment]
I upgraded bitwarden to 1.34 from 1.33

I did the upgrade like this


vi /bitwarden/bwdata/docker/docker-compose.yml


make sure you change these lines


api:
    image: bitbetter/api


to


api:
    image: bitwarden/api:latest


and


identity:
    image: bitbetter/identity


to


identity:
    image: bitwarden/identity:latest


run this


cd /bitwarden/bwdata/docker/

docker-compose pull && docker-compose up -d


will update, once updated change the above back so we can use organisations ie groups


then run this


cd /bitwarden/bwdata/docker/

docker-compose up -d

then I couldn't make any new items, I imagine as I'm using the bitbetter api and not the bitwarden one, to resolve I did this

mv /bitwarden/bwdata/BitBetter/ /bitwarden/backup/


cd /bitwarden/bwdata/


git clone https://github.com/jakeswenson/BitBetter.git


/bitwarden/bwdata/BitBetter/build.sh


/bitwarden/bwdata/BitBetter/src/licenseGen/build.sh


cd /bitwarden/bwdata/docker/


docker-compose up -d

hope this helps

**Comment by GieltjE** [comment]
Or just use the excellent script by h44z, that will fix these problems too.

**Comment by robina80** [comment]
Where's this script please?

**Comment by dns13** [comment]
See the PR from h44z, will be merged soon.

**Comment by JeffAlyanak** [comment]
> Where's this script please?

https://github.com/jakeswenson/BitBetter/pull/69

This will be merged soon, there's an issue with the CI that needs to be fixed and only Jake can fix that.

**Comment by robina80** [comment]
thanks all,

so does that mean when I update my instance of bitwarden in future I really need to check if there's a new version of bit better as it's using the api of bit better

I know I can change it back to bitwarden api and it will work again

**Comment by GieltjE** [comment]
In the future we would only need to do a git pull on the BitBetter repository and then run the new ./update-bitwarden.sh script.
Maybe we can add something to the update-bitwarden.sh script to make it update the current repository if it isn't up to date @h44z?

**Comment by dns13** [comment]
We could add an „updateself“ to be compliant to the Bitwarden way of doing this.

**Comment by robina80** [comment]
the only issue i have with this is as i have built bitwarden the manual way ie using the "manual docker installations" i dont have in my "bwdata"

./bitwarden.sh updateself
./bitwarden.sh update

the only way i could update, is how i said above, ie change the api/identity back to bitwarden and run the below in my "docker" dir

docker-compose pull && docker-compose up -d

as this updates all the bitwarden docker images but obviously doesnt update the bitbetter images

**Comment by tam481** [comment]
hi @robina80 
You should use the docker-compose.override.yml file for that rather than modifying the docker-compose.yml file every time you update.

**Comment by GieltjE** [comment]
@robina80 So you are not using the original bitwarden.sh file?

**Comment by robina80** [comment]
thanks @tam481 for that good info

no @GieltjE instead of installing bitwarden like Im using the stubbed version 

https://github.com/bitwarden/server/releases

and in there there's no script to auto update

**Comment by GieltjE** [comment]
Why are you manually installing the docker versions? And where do you keep the data normally stored in bwdata?

**Comment by robina80** [comment]
because at first i installed bitwarden behind the firewall with no internet access and it couldnt pull any dockers so i made a script to pull the dockers and then take it offline

heres my script if interested

`#!/bin/bash

mkdir /dockers

cd /dockers

docker pull bitwarden/web
docker save bitwarden/web:latest > bitwarden.web:latest.tar
docker load < bitwarden.web:latest.tar
docker pull bitwarden/mssql
docker save bitwarden/mssql:latest > bitwarden.mssql:latest.tar
docker load < bitwarden.mssql:latest.tar
docker pull bitwarden/nginx
docker save bitwarden/nginx:latest > bitwarden.nginx:latest.tar
docker load < bitwarden.nginx:latest.tar
docker pull bitwarden/admin
docker save bitwarden/admin:latest > bitwarden.admin:latest.tar
docker load < bitwarden.admin:latest.tar
docker pull bitwarden/events
docker save bitwarden/events:latest > bitwarden.events:latest.tar
docker load < bitwarden.events:latest.tar
docker pull bitwarden/notifications
docker save bitwarden/notifications:latest > bitwarden.notifications:latest.tar
docker load < bitwarden.notifications:latest.tar
docker pull bitwarden/icons
docker save bitwarden/icons:latest > bitwarden.icons:latest.tar
docker load < bitwarden.icons:latest.tar
docker pull bitwarden/attachments
docker save bitwarden/attachments:latest > bitwarden.attachments:latest.tar
docker load < bitwarden.attachments:latest.tar
docker pull bitwarden/identity
docker save bitwarden/identity:latest > bitwarden.identity:latest.tar
docker load < bitwarden.identity:latest.tar
docker pull bitwarden/api
docker save bitwarden/api:latest > bitwarden.api:latest.tar
docker load < bitwarden.api:latest.tar
docker pull bitwarden/setup
docker save bitwarden/setup:latest > bitwarden.setup:latest.tar
docker load < bitwarden.setup:latest.tar
docker pull bitwarden/server
docker save bitwarden/server:latest > bitwarden.server:latest.tar
docker load < bitwarden.server:latest.tar
docker run -d `bitwarden/web`

once i ran that i took it offline so bitwarden can work offline

**Comment by GieltjE** [comment]
Bitwarden can easily work offline with the default .sh script, just comment the pull parts.
Since you still have a regular bwdata directory it might be better to migrate to a normal docker installation.

**Comment by robina80** [comment]
sorry i only ran this script once, when i first installed it and never again as your right i dont want to pull and overwrite my data

**Comment by GieltjE** [comment]
It doesn't overwrite data, that's where the bwdata directory is for, docker only contains the runtime environment.

**Comment by robina80** [comment]
so for example in my script the mssql commands ie the pull/save/load won't overwrite my files as there the run times for the mssql environment?

**Comment by h44z** [comment]
> so for example in my script the mssql commands ie the pull/save/load won't overwrite my files in the "bwdata" dir as there the run times for the mssql environment?

As long as your docker-compose.yml specifies volumes, for example:

```    
volumes:
      - ../mssql/data:/var/opt/mssql/data
      - ../logs/mssql:/var/opt/mssql/log
      - ../mssql/backups:/etc/bitwarden/mssql/backups
```
your data is stored outside the container. Thus deleting/updating the container image wont delete your data, as only the container gets recreated and your data is mounted to it afterwards.

So make sure that your docker-compose.yml contains the volume configurations for mssql, attachments and the other containers. And of course, always make a backup before you update!

**Comment by Ikallin** [comment]
Hi all,
I notice similarities between the comments in this post and my problems.
I have bitwarden in version 1.33.0 and associated bitbetter.

Everything works fine until I add bitbetter, I can't create any more items, notes, ids etc... I found an error in API with "cipher_details_create" and something like "too many arguments".

I've tried a lot of things, but nothing I can do. I didn't dare to create a new post and maybe some of you have already solved this problem.
Thank you in advance :)

**Comment by GieltjE** [comment]
Update to 1.34 and use h44z's .sh script to update

**Comment by Ikallin** [comment]
Thanks @GieltjE, Seems to be solved after some fixes. Had to remove version "1.34.0" after bitbetter images in the docker file.

Thanks again !

**Comment by GieltjE** [comment]
Fixed in recent commits
