### ISSUE TITLE
Multi-Oranizations issue

### ISSUE THREAD

**Issue by Ikallin** [jakeswenson/BitBetter#71]
Hello, I have an existing installation of Bitwarden/Bitbetter that has an organization and everything is working great.

I would like to create a brand new Org that is totally dissociate with the first one I have created.

So, I tried to re-generate by building and process as I did for the first, but the UI is throwing me an error like "Invalid License".
I didn't found an issue about it and would like to solve this.
Do you have any advice/tips that I maybe did wrong ?

Thanks for the time you accorded to this post :)

**Comment by captainhook** [comment]
You'll need to provide some more information to help understand your setup. Run `docker ps` and share output please.

**Comment by Ikallin** [comment]
Hi,

Here it is : 
![docker-ps-github](https://user-images.githubusercontent.com/66952596/87927512-9d7d9100-ca83-11ea-834e-5bb319b340e2.png)

Hope it helps 👍

**Comment by captainhook** [comment]
Looks like you are running the right containers.
How are you generating your org licenses?

**Comment by Ikallin** [comment]
I did the things on the main page ( ./build.sh from main directory, ./build.sh from src/licenceGen and finally .run.sh interactive)

The one that I generated works great and got accepted at the first try

**Comment by captainhook** [comment]
Not an issue with Bitbetter so I'll close this issue.
