### ISSUE TITLE
Invalid License

### ISSUE THREAD

**Issue by mrventerj** [jakeswenson/BitBetter#78]
When I go to New Organization and upload the .json file I get a :
An error has occurred.
Invalid license.

Any ideas?

Edit:  Noticed after running the initial build.sh - there is no keys folder created?

**Comment by captainhook** [comment]
Have you built the licenseGen tool? How did you generate/obtain the json file?
Run `docker ps` and share the output.
In your BitBetter directory, run `ls -all` and share the output.

**Comment by mrventerj** [comment]
I ran some of the steps again -  it was either that or that in the .json file  I think i had my username the same as my email- I changed my username back without the @myemail. domain - did a restart - after reboot - it accepted the license file!

Sorry to bother you gents with peasant rookie mistakes.

Keep on doing Gods work.<3 Much appreciated.
