### ISSUE TITLE
Docker Interface overlap with Local LAN

### ISSUE THREAD

**Issue by mrventerj** [jakeswenson/BitBetter#79]
My LAN is 172.28.0.0\16 and its route should be 10.3.0.1

It seems that the docker is conflicting with the LAN - can and how do I change the subnet for docker?

Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         10.3.0.1        0.0.0.0         UG        0 0          0 eth0
10.3.0.0        0.0.0.0         255.255.255.0   U         0 0          0 eth0
168.63.129.16   10.3.0.1        255.255.255.255 UGH       0 0          0 eth0
169.254.169.254 10.3.0.1        255.255.255.255 UGH       0 0          0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U         0 0          0 docker0
172.28.0.0      0.0.0.0         255.255.0.0     U         0 0          0 br-828c78b615e2
172.29.0.0      0.0.0.0         255.255.0.0     U         0 0          0 br-adff3a5cad70

**Comment by h44z** [comment]
Hi, this is not really related to BitBetter. 

You could either change the network in the docker-compose override file (see https://docs.docker.com/compose/networking/).
Or you can change the docker default network (https://docs.docker.com/network/).

**Comment by mrventerj** [comment]
Solved the issue:  - thanks for sending me in the right direction h44z <3:

I was able to mitigate the conflict with the default network created by my docker config.

 add changes to docker-compose.override.yml

The changes from the override file are merged with the original file.

I used the below in the override file to move away from the 172 -> 173 which opened up my 172 Local Lan to the default GW:

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 173.28.0.0/16
I then also had to remove the old docker network with:

sudo docker network rm "id-of-nw"

The ID can be retrieved with the combination of:

sudo docker network ls

and

route

**Comment by h44z** [comment]
@mrventerj Glad it worked out for you. A small hint: the 173.x.x.x subnet is a public subnet. This means that you might encounter some connectivity issues for example some internet sites might not be reachable any longer.
See: https://en.wikipedia.org/wiki/Private_network#Private_IPv4_addresses
