### ISSUE TITLE
cp: cannot create regular file '/jobs/Core.dll': No such file or directory

### ISSUE THREAD

**Issue by online-stuff** [jakeswenson/BitBetter#8]
Alright..

Started again on fresh/clean Debian Stretch system.

I am running  ~/BitBetter/build.sh

I am getting this error at the end of the output.

modified dll
cp: cannot create regular file '/jobs/Core.dll': No such file or directory
The command '/bin/sh -c dotnet /bitBetter/bitBetter.dll &&     echo "modified dll" &&     mv /app/Core.dll /app/Core.orig.dll &&     mv /app/modified.dll /app/Core.dll &&     cp -f /app/Core.dll /jobs/Core.dll &&     echo "replaced dll" &&     rm -rf /bitBetter && rm -rf /newLicensing.cer &&     echo "cleaned up"' returned a non-zero code: 1

I have kept track of every command I have entered..  Hopefully when I have this working we can make a better install manual...  ;)

**Comment by mbrackjr** [comment]
have the same problem; i'm not knowledgeable enough on this to rectify the code myself, but am available to help test and validate.

**Comment by online-stuff** [comment]
I'm working on this now..  Think I found the problem, so I may have this fixed..  But I'll work on this tonight and see if I can improve a few things.  :)  Unless the author has a fix  :)

**Comment by online-stuff** [comment]
I made a few changes to fix many issues.

https://github.com/online-stuff/BitBetter

Jake can pull them if he wants..

**Comment by h44z** [comment]
I have also done some research on this problem. As I found out, bitwarden as of version 1.23 does not contain the jobs directory any more. See commit: https://github.com/bitwarden/core/commit/10a19c90d333b78f966f29c7a9c9291569604d85#diff-32a6f62bd8463be7df4856ef593270ba
So there is no need to create this directory and copy the dll in.

**Comment by johnczer** [comment]
Could you please tell me where or if there is actually an organization.json or similar license file generated and where do I find this?  Or is this license somehow added automatically after following these steps. Each time I run through the steps and log back in to see if the generated license was applied it appears that it has not. I also do not see where to upload a license.json if one actually exist. I have spent hours on this and I am sorry but not a coder.  Thanks

**Comment by online-stuff** [comment]
After generating, copy&paste the output to a file, then in the web-interface, upload the license file you created

**Comment by johnczer** [comment]
ok, I did that and named the file xxxx.json but when I try to upload it says license invalid. Ughh...

**Comment by johnczer** [comment]
Got it!  Thanks for your help!

**Comment by DanielCambray** [comment]
I also have a "license invalid" message. What did you do ?
