### ISSUE TITLE
Android:CertPathValidatorExeption

### ISSUE THREAD

**Issue by nagy511** [jakeswenson/BitBetter#81]
# Issue

On Android 10+ maybe in earlier versions,
The trusted Anchor parh could not be verified/found. 

On desktop  anything works correctly,
Have someone the same issue ? 

I dount know if this have something  to do with the self signed cert or my reverse  proxy in combination  with the Android security  rules.

**Comment by nagy511** [comment]
#AndoidAPP

**Comment by captainhook** [comment]
This is not a BitBetter issue.

Please do a google search for 'Bitwarden' + the error message, there are posts about it from about a year ago with various solutions.
