### ISSUE TITLE
Issue generating a org cert 

### ISSUE THREAD

**Issue by KenwoodFox** [jakeswenson/BitBetter#82]
Hello, im trying to run licenceGen as described in the readme but im getting this error.
```# ./src/licenseGen/run.sh interactive
Unable to find image 'bitbetter/licensegen:latest' locally
docker: Error response from daemon: pull access denied for bitbetter/licensegen, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.```
Thanks for reading, im looking forward to solving it.

**Comment by alexyao2015** [comment]
Try reading the documentation again. You need to first build it as the images are not public

**Comment by KenwoodFox** [comment]
I'm not sure what you mean, I did build it. Just as the documentation describes.

**Comment by alexyao2015** [comment]
You need to build the license generator. The message you are seeing is indicative that the license generator was not built.

**Comment by KenwoodFox** [comment]
I used `./build.sh` to build the license generator?
The instructions don't say to do anything else for building it.

**Comment by alexyao2015** [comment]
Hmm yeah the documentation says this which is wrong
`First, from the BitBetter directory, build the license generator`
Should say from the `licenseGen directory`.

**Comment by KenwoodFox** [comment]
Ah, ok that makes more sense, should that get updated?

**Comment by alexyao2015** [comment]
Hopefully. I'm not a contributor here so I can't make changes.

**Comment by KenwoodFox** [comment]
Created a PR for it, thanks @alexyao2015
