### ISSUE TITLE
bitbetter/licensegen don't exist

### ISSUE THREAD

**Issue by tvatry** [jakeswenson/BitBetter#86]
Hello,
When I lunch `./src/licenseGen/run.sh interactive` an error is displayed `docker: Error response from daemon: pull access denied for bitbetter/licensegen, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.`

**Comment by h44z** [comment]
Hi, did you build the licenseGen tool? I think https://github.com/jakeswenson/BitBetter/issues/82 is related to this issue.

**Comment by captainhook** [comment]
@h44z is correct, you haven't built BitBetter so you need to go through the steps again. This has been answered several times already: https://github.com/jakeswenson/BitBetter/issues?q=is%3Aissue+repository+does+not+exist
