### ISSUE TITLE
get error when run run.sh license gen

### ISSUE THREAD

**Issue by robina80** [jakeswenson/BitBetter#91]
hi all,

get this error when im running the run.sh script while trying to generate an organisation 

`/bitwarden/bwdata/BitBetter-master/src/licenseGen/run.sh /bitwarden/bwdata/BitBetter-master/.keys/cert.pfx
Specify --help for a list of available options and commands.
Oops: Microsoft.Extensions.CommandLineUtils.CommandParsingException: Unrecognized command or argument '/bitwarden/bwdata/BitBetter-master/.keys/cert.pfx'
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.HandleUnexpectedArg(CommandLineApplication command, String[] args, Int32 index, String argTypeName)
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at bitwardenSelfLicensor.Program.Main(String[] args) in /licenseGen/Program.cs:line 286`

any help would be much appreciated

thanks,
rob

**Comment by captainhook** [comment]
Please read the documentation.

You need to run in either interactive mode:
https://github.com/jakeswenson/BitBetter#generating-signed-licenses

or with arguments:
https://github.com/jakeswenson/BitBetter#note-alternative-ways-to-generate-license

**Comment by robina80** [comment]
ok when i run it interactive it works but manual it doesnt?

`/bitwarden/bwdata/BitBetter-master/src/licenseGen/run.sh /bitwarden/bwdata/BitBetter-master/.keys/cert.pfx org robert robertkwild@gmail.com install-id`

what am i doing wrong

**Comment by captainhook** [comment]
What error do you get? Is that definitely the absolute path? Try encapsulating the arg values in double quotes like in the documentation.

**Comment by robina80** [comment]
ive tried with quatations but no luck

`/bitwarden/bwdata/BitBetter-master/src/licenseGen/run.sh /bitwarden/bwdata/BitBetter-master/.keys/cert.pfx org "robert" "robertkwild@gmail.com" "install-id"`

`Oops: System.ArgumentNullException: Value cannot be null. (Parameter 's')
   at System.Double.Parse(String s)
   at bitwardenSelfLicensor.Program.<>c__DisplayClass0_3.<Main>b__9() in /licenseGen/Program.cs:line 261
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at bitwardenSelfLicensor.Program.Main(String[] args) in /licenseGen/Program.cs:line 286`

**Comment by robina80** [comment]
ok i know the problem, its the storage value but how do i put that in the string, do i put it in after or before the installation id?

**Comment by captainhook** [comment]
Type `pwd` in your shell and share the output

**Comment by robina80** [comment]
ok i have done it and it works!!!!!!!!!

`/bitwarden/bwdata/BitBetter-master/src/licenseGen/run.sh /bitwarden/bwdata/BitBetter-master/.keys/cert.pfx org "robert" "robertkwild@gmail.com" "c8187ea1-f8e4-4be7-ae07-aaef00a153c6" 0`

but instead of 0 for storage what is the wildcard for unlimited?
