### ISSUE TITLE
orgs disabled after updating bitwarden and bitbetter

### ISSUE THREAD

**Issue by robina80** [jakeswenson/BitBetter#92]
hi all,

everytime i update bitwarden to the latest server/web and sometimes when i do the bitbetter api doesnt work so i have to update bitbetter as well, so i do the following to update bitbetter

`cd /bitwarden/bwdata/`
`wget https://github.com/jakeswenson/BitBetter/archive/master.zip`
`unzip master.zip`
`cd BitBetter-master/`
`./build.sh`
`cd src/licenseGen/`
`./build.sh`

problem is when i do the organisations i have made using the old bitbetter get disabled, is there anything i can do for this to stop happening?

do i have to copy the old license to the new bitbetter dir for the old orgs to work?

`/bitwarden/bwdata/BitBetter-master/.keys/cert.pfx`

thanks,
rob

**Comment by robina80** [comment]
maybe if i do this...

as you can see below (in pic) theres an option to update the license for the org

![org](https://user-images.githubusercontent.com/16721957/107507150-0e5ad680-6b97-11eb-9c3e-96c7ef5cf11e.PNG)

how about i make a new org (using the bitbetter script) edit the new json file, leave the“license key” “installation id” the same but only change the "id" field

will this stop it from being disabled and then i can re use the org?

thanks,
rob

**Comment by captainhook** [comment]
Licenses are based on the private keys. You need to keep those safe and use them when you generate the licenses/BitBetter images.

**Comment by robina80** [comment]
so the above, wont work captainhook?

where are the private keys held

**Comment by captainhook** [comment]
The private key is the cert.pfx file

**Comment by robina80** [comment]
so if i run this again

`cd src/licenseGen/`
`./build.sh`

as this will overwrite my key, i need to copy my old cert.pfx in the new dir here

ls /bitwarden/bwdata/BitBetter-master/.keys/
cert.cert  cert.pem  cert.pfx  generate-keys.sh  key.pem

**Comment by captainhook** [comment]
No, that will not overwrite your private key, that will use your private key to generate a license.
You are having the license issue because you are using completely different private keys. When you update BitBetter, copy your old private key to the keys folder.

**Comment by robina80** [comment]
so do i copy just the "cert.pfx" file over to the new dir or the whole bunch of files ie cert.cert, cert.pem etc

sorry for the daft questions

**Comment by captainhook** [comment]
Just your cert.pfx:
https://github.com/jakeswenson/BitBetter#note-alternative-ways-to-generate-license

**Comment by robina80** [comment]
I imagine I can't re enable the old org as I didn't save the old cert.pfx file as thats how I created the old org

So it will always be disabled?

**Comment by captainhook** [comment]
Unfortunately not. You can generate a new license for that org and just import it into that org to reactivate it.
