### ISSUE TITLE
Running update-bitwarden.sh when no updates are available produces untagged images.

### ISSUE THREAD

**Issue by FingerlessGlov3s** [jakeswenson/BitBetter#93]
Hi Guys,

If you update bitwardening using the update-bitwarden.sh when there isn't an update available, it'll create new bitbetter images and because its using the same tags of the old images, the old images become untagged and there therefore not deleted.

Therefore you couldn't really run this on a nightly basis to update bitwarden because it would would create lots of untagged images over time.

`/opt/bitbetter/update-bitwarden.sh /opt/bitwarden/ y y`

```
bitbetter/identity                  1.39.4    075dc7d956c8   About a minute ago   375MB
bitbetter/identity                  latest    075dc7d956c8   About a minute ago   375MB
bitbetter/api                       1.39.4    706654fbbdda   About a minute ago   378MB
bitbetter/api                       latest    706654fbbdda   About a minute ago   378MB
<none>                              <none>    0a0f70579bda   5 minutes ago        375MB <-- should be deleted
<none>                              <none>    a1ee97cb8a83   5 minutes ago        378MB <-- should be deleted
```

**Comment by h44z** [comment]
Should be resolved with #95
