### ISSUE TITLE
Invalid License File

### ISSUE THREAD

**Issue by indaleco** [jakeswenson/BitBetter#94]
I'm sure I'm doing something wrong, but hoping for some direction.

I've ran through the instructions.  Did the build for bitbetter.  Created the docker compose override file.  Updated the run.sh and commented out docker pull.  Built the license generator.  Ran the license generator.  When I upload the license I got from the generator, it says file invalid.  

My initial question is when I save this as a JSON - I'm saving it in notepad, and keeping the brackets.   But any further advice would be appreciated.  Thanks so much!

**Comment by Beyley** [comment]
I get a similar error "Version 6 is not supported"

**Comment by captainhook** [comment]
Can you both please share your license files and screenshots of the error messages?

**Comment by Radek-Suski** [comment]
Having most likely same issue. Here is the file:

```

{
  "LicenseKey": "a157e84d817e4df695d742ca1f9e7f36",
  "InstallationId": "2f9868eb-e62a-45e1-874b-ad4200ba2732",
  "Id": "88edf56c-e3ec-4895-bd98-6db606a54111",
  "Name": "Radek Suski",
  "BillingEmail": "a@b.c",
  "BusinessName": "Company name",
  "Enabled": true,
  "Plan": "Custom",
  "PlanType": 6,
  "Seats": 32767,
  "MaxCollections": 32767,
  "UsePolicies": true,
  "UseSso": true,
  "UseGroups": true,
  "UseEvents": true,
  "UseDirectory": true,
  "UseTotp": true,
  "Use2fa": true,
  "MaxStorageGb": 32767,
  "SelfHost": true,
  "UsersGetPremium": true,
  "Version": 6,
  "Issued": "2021-06-09T14:51:58.7973141Z",
  "Refresh": "2121-05-09T14:51:58.7974979Z",
  "Expires": "2121-06-09T14:51:58.8040937Z",
  "Trial": false,
  "UseApi": true,
  "Hash": "x0JjKleIf4RweCY5+iTEhd8VbLBT+WQg+BdDbisIZtI=",
  "Signature": "hOIgWdw09fIKJz/DWdlyrsjtZkl+cSxsSCrebcS0wnP9CJ3CVRuWiOtPhGqHth2Ne7fz0rQDQuM7kKRnxCR4YQyG5ni06w8dSRkhgusPYAJi4p734ud721zb9XDQFK5pvKsem8SYsZUmzZhr6Dhc8y+ExznOw00a4L53uTz9OagI0bEzdkQWqGB50odlVRBOX1itWt68bT5E2JO0seCdfdzd1h4ZGewJbgnLiWZoEgQWGExh0nv6Ym8DhKoNoUN3C4nMHuvit8z0+7UtaPSTOz9KCX3sxYUMOWc4c/8Hv/ExSXoEgKg/Gld2knP7MtUCjbkjNtNPYMBWMnEA4LhXjKCscjT6B2ld7a5n1lf+sSPVRFJJJJWb/pI+15LVBL7J7Bl0af49Xj3aHO5luT7ClEZu+gR1URum0tYMSJllbB8qaOlhzlWSY6gdZQnKHesMW/y2+BDZxwu5/KW1twOZ6AqzGvCqxNdeVXg3Z5GiX8irL4gSPi9d4pr3oIgd7lWooVV4RmDCKiZ+Z2CdqPQPEuKuInfsDDvtgrVSJ5Z/yQ5+HDPrBsrvx52B0FvG4LD5NVDvHILkk8iQ4MujH+VQd+rxy33VZD8torXYkHJAE7FkYSLq+heNur4J8Oc/xu9XJqFTFXVYUlIwOVGBoO7i2iDFJJ6j2tuUVWTO5B4bcaI="
}

```

<img width="355" alt="Screen Shot 2021-06-09 at 16 58 06" src="https://user-images.githubusercontent.com/1110663/121378912-e2344400-c943-11eb-969e-d14be0ee0d97.png">

**Comment by Radek-Suski** [comment]
Ok, I've re-run all steps from the beginning and it works now so obviously I screwed something. Thanks a lot
