### ISSUE TITLE
API: Have I Been Pwned issue - 401

### ISSUE THREAD

**Issue by Javinator9889** [jakeswenson/BitBetter#96]
While trying to use Bitwarden tools for viewing leaks, the server responses with a `401` error.

This is directly related (I think) to the API, as it is communicating with the Have I Been Pwned website (see picture below):
![image](https://user-images.githubusercontent.com/25952165/112718589-5b4efe00-8ef4-11eb-9c79-27322bcc2946.png)

Using latest BitBetter (1.40.0) and Bitwarden images

**Comment by h44z** [comment]
This has nothing to do with BitBetter. BitBetter only modifies the license checking part of the API image. Please report this bug directly to Bitwarden.

**Comment by Javinator9889** [comment]
Thanks for the info, will report ^^
