### ISSUE TITLE
Error response from daemon: conflict: unable to delete

### ISSUE THREAD

**Issue by robina80** [jakeswenson/BitBetter#97]
hi all,

when i try to update bitbetter via downloading a new bitbetter-master.zip, unzipping it and running the build script, i get this error

Error response from daemon: conflict: unable to delete f74a3df8abc4 (cannot be forced) - image has dependent child images

before i update everything i do a prune to get rid of old images etc

docker system prune
docker system prune --volumes

but im still getting this error after i prune dockers

thanks,
rob

**Comment by Beyley** [comment]
Hey, im wondering how did you fix this? im getting this issue
